[package]
name = "linguini-cldr-macros"
version = "0.1.0-alpha.4"
description = "Offline generator for Linguini's checked-in CLDR data"
readme = "README.md"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
linguini-cldr = { path = "../linguini-cldr", version = "0.1.0-alpha.4" }
proc-macro2 = "1.0"
quote = "1.0"
serde_json = "1.0.149"

[dev-dependencies]
linguini-test-support = { path = "../linguini-test-support", version = "0.1.0-alpha.4" }
