[package]
name = "linguini-cldr"
version = "0.1.0-alpha.4"
description = "Compiled CLDR plural and formatting data for Linguini"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
include = ["Cargo.toml", "src/**", "UNICODE-LICENSE.txt"]

[dev-dependencies]
linguini-test-support = { path = "../linguini-test-support" }
serde_json = "1.0.149"
