//! Offline generator for Linguini's checked-in CLDR data artifact.
//!
//! This crate is a maintainer tool. It is never a build dependency of
//! `linguini-cldr`, and generation only runs through the explicit CLI.

mod formatting;
mod locale;
mod sha256;
mod source;
mod source_paths;

use serde_json::json;
use sha256::{digest, hex};
use source::generate_compiled_tables;
use source_paths::{
    CldrSource, CLDR_VERSION, SOURCE_COMMIT, SOURCE_GIT_TREE, SOURCE_REF, SOURCE_REPOSITORY,
    UNICODE_VERSION,
};
use std::fs;
use std::path::Path;

pub const ARTIFACT_FILE: &str = "cldr_tables.rs";
pub const MANIFEST_FILE: &str = "manifest.json";

pub fn generate(source_root: &Path, output_dir: &Path, check: bool) -> Result<(), String> {
    let source = CldrSource::open(source_root)?;
    let generated = generate_compiled_tables(&source)?;
    source.verify_unchanged()?;
    let mut artifact =
        "// @generated by linguini-cldr-macros; verify with adjacent manifest.json.\n".to_owned();
    artifact.push_str(&generated.tokens.to_string());
    artifact.push('\n');
    let artifact_sha256 = hex(&digest(artifact.as_bytes()));
    let artifact_bytes = artifact.len() as u64;

    let manifest = json!({
        "schema": 1,
        "generator": {
            "name": "linguini-cldr-macros",
            "artifact_schema": 1
        },
        "source": {
            "repository": SOURCE_REPOSITORY,
            "ref": SOURCE_REF,
            "commit": SOURCE_COMMIT,
            "git_tree": SOURCE_GIT_TREE,
            "cldr_version": CLDR_VERSION,
            "unicode_version": UNICODE_VERSION,
            "license": "Unicode-3.0"
        },
        "inputs": {
            "profile": "locale-aliases+parent-locales+likely-subtags+bcp47-extension-aliases+plurals+currency-fractions+latn-numbers+latn-currency+gregorian+layout-v3",
            "tree_hash_algorithm": "sha256; domain=linguini-cldr-source-tree-v1\\0; repeated=u64be(path_len)||path||u64be(file_len)||file_bytes",
            "tree_sha256": source.source_tree_sha256(),
            "file_count": source.input_file_count(),
            "bytes": source.input_bytes()?
        },
        "artifact": {
            "path": ARTIFACT_FILE,
            "sha256": artifact_sha256,
            "bytes": artifact_bytes
        },
        "coverage": {
            "source_locales": source.locales().len(),
            "plural_locales": generated.plural_locales,
            "plural_categories": generated.plural_categories,
            "language_aliases": generated.locale.language_aliases,
            "script_aliases": generated.locale.script_aliases,
            "territory_aliases": generated.locale.territory_aliases,
            "variant_aliases": generated.locale.variant_aliases,
            "parent_locales": generated.locale.parent_locales,
            "locale_rules": generated.locale.locale_rules,
            "likely_subtags": generated.locale.likely_subtags,
            "extension_key_aliases": generated.locale.extension_key_aliases,
            "extension_type_aliases": generated.locale.extension_type_aliases,
            "locale_candidates": generated.locale.locale_candidates,
            "number_locales": generated.formatting.number_locales,
            "currency_locales": generated.formatting.currency_locales,
            "currency_fraction_rules": generated.formatting.currency_fraction_rules,
            "date_locales": generated.formatting.date_locales,
            "text_direction_locales": generated.formatting.text_direction_locales,
            "excluded": {
                "date": generated.formatting.date_exclusions.iter().map(|locale| json!({
                    "locale": locale,
                    "reason": "short date uses unsupported M=romanlow numbering override"
                })).collect::<Vec<_>>(),
                "text_direction": generated.formatting.text_direction_exclusions.iter().map(|locale| json!({
                    "locale": locale,
                    "reason": "vertical top-to-bottom layout is not representable as ltr/rtl"
                })).collect::<Vec<_>>()
            }
        }
    });
    let mut manifest =
        serde_json::to_string_pretty(&manifest).map_err(|error| error.to_string())?;
    manifest.push('\n');

    if check {
        check_file(&output_dir.join(ARTIFACT_FILE), artifact.as_bytes())?;
        check_file(&output_dir.join(MANIFEST_FILE), manifest.as_bytes())?;
        return Ok(());
    }

    fs::create_dir_all(output_dir).map_err(|error| format!("{}: {error}", output_dir.display()))?;
    fs::write(output_dir.join(ARTIFACT_FILE), artifact)
        .map_err(|error| format!("{}: {error}", output_dir.join(ARTIFACT_FILE).display()))?;
    fs::write(output_dir.join(MANIFEST_FILE), manifest)
        .map_err(|error| format!("{}: {error}", output_dir.join(MANIFEST_FILE).display()))?;
    Ok(())
}

fn check_file(path: &Path, expected: &[u8]) -> Result<(), String> {
    let actual = fs::read(path).map_err(|error| format!("{}: {error}", path.display()))?;
    if actual == expected {
        Ok(())
    } else {
        Err(format!(
            "{} differs from deterministic CLDR generation output",
            path.display()
        ))
    }
}

#[cfg(test)]
mod tests {
    use super::sha256::{digest, hex};
    use serde_json::Value;

    const CHECKED_ARTIFACT: &[u8] =
        include_bytes!("../../linguini-cldr/src/data/generated/cldr_tables.rs");
    const CHECKED_MANIFEST: &[u8] =
        include_bytes!("../../linguini-cldr/src/data/generated/manifest.json");
    const GOLDEN_ARTIFACT_SHA256: &str =
        "d5a6acab50bf98cd05ba2087b92cba64b9832e6fdf9e530d1dd7ab9648a7a1ca";
    const GOLDEN_MANIFEST_SHA256: &str =
        "36362a2a8668531b3ae02ca15ef18a9264376ea67b79b9950e3ede0fabdf7f69";

    #[test]
    fn checked_artifact_matches_full_pinned_manifest_and_golden_hash() {
        assert_eq!(hex(&digest(CHECKED_ARTIFACT)), GOLDEN_ARTIFACT_SHA256);
        assert_eq!(hex(&digest(CHECKED_MANIFEST)), GOLDEN_MANIFEST_SHA256);

        let manifest: Value = serde_json::from_slice(CHECKED_MANIFEST).expect("manifest JSON");
        assert_eq!(manifest["schema"], 1);
        assert_eq!(manifest["artifact"]["path"], "cldr_tables.rs");
        assert_eq!(
            manifest["artifact"]["bytes"].as_u64(),
            Some(CHECKED_ARTIFACT.len() as u64)
        );
        assert_eq!(manifest["artifact"]["sha256"], GOLDEN_ARTIFACT_SHA256);
        assert_eq!(manifest["source"]["cldr_version"], "48.2.0");
        assert_eq!(
            manifest["source"]["commit"],
            "bb334e8d6250c9363e957e131bf7e6d08ec72f91"
        );
        assert_eq!(
            manifest["source"]["git_tree"],
            "b297a9501ae136e59d006f0497204524a5478cc9"
        );
        assert_eq!(
            manifest["inputs"]["tree_sha256"],
            "56a882b24a6f978d514c6940afd18f96d9b9078b7d967b3f6b4d76b5516387b5"
        );
        assert_eq!(manifest["inputs"]["file_count"], 2_323);
        assert_eq!(manifest["coverage"]["source_locales"], 766);
        assert_eq!(manifest["coverage"]["language_aliases"], 500);
        assert_eq!(manifest["coverage"]["script_aliases"], 1);
        assert_eq!(manifest["coverage"]["territory_aliases"], 640);
        assert_eq!(manifest["coverage"]["variant_aliases"], 2);
        assert_eq!(manifest["coverage"]["parent_locales"], 199);
        assert_eq!(manifest["coverage"]["locale_rules"], 1);
        assert_eq!(manifest["coverage"]["likely_subtags"], 7_788);
        assert_eq!(manifest["coverage"]["extension_key_aliases"], 0);
        assert_eq!(manifest["coverage"]["extension_type_aliases"], 49);
        assert_eq!(manifest["coverage"]["locale_candidates"], 8_460);
        assert_eq!(manifest["coverage"]["plural_locales"], 224);
        assert_eq!(manifest["coverage"]["plural_categories"], 499);
        assert_eq!(manifest["coverage"]["number_locales"], 766);
        assert_eq!(manifest["coverage"]["currency_locales"], 766);
        assert_eq!(manifest["coverage"]["currency_fraction_rules"], 75);
        assert_eq!(manifest["coverage"]["date_locales"], 765);
        assert_eq!(manifest["coverage"]["text_direction_locales"], 764);
    }

    #[test]
    fn artifact_hash_detects_tampering() {
        let mut tampered = CHECKED_ARTIFACT.to_vec();
        let midpoint = tampered.len() / 2;
        tampered[midpoint] ^= 1;
        assert_ne!(hex(&digest(&tampered)), GOLDEN_ARTIFACT_SHA256);
    }

    #[test]
    fn runtime_crate_consumes_only_checked_in_data() {
        let generator_manifest = include_str!("../Cargo.toml");
        let runtime_manifest = include_str!("../../linguini-cldr/Cargo.toml");
        let runtime_compiled = include_str!("../../linguini-cldr/src/data/compiled.rs");
        let source_paths = include_str!("source_paths.rs");

        assert!(!generator_manifest.contains("proc-macro = true"));
        assert!(generator_manifest.contains("publish = false"));
        assert!(!runtime_manifest.contains("linguini-cldr-macros"));
        assert!(runtime_compiled.contains("include!(\"generated/cldr_tables.rs\")"));
        for forbidden in [
            concat!("Command", "::new"),
            concat!("remove_dir", "_all"),
            concat!("LINGUINI_CLDR_", "AUTO_FETCH"),
            concat!("LINGUINI_CLDR_", "SOURCE_CHECKOUT_DIR"),
            concat!("fetch_cldr", "_json"),
            concat!("CldrFetch", "Lock"),
        ] {
            assert!(
                !source_paths.contains(forbidden),
                "offline generator still contains forbidden build-time operation `{forbidden}`"
            );
        }
    }
}
