use linguini_cldr::{
    load_currency_formatting_from_cache, load_date_formatting_from_cache,
    load_number_formatting_from_cache, load_plural_rules_from_cache, CldrCacheResult, Condition,
    FormatWidths, Operand, OperandExpression, PluralRule, Range, Relation, RelationOperator,
};
use std::path::Path;

pub(crate) fn generate_compiled_tables_from_cache(
    cache_root: impl AsRef<Path>,
    locales: Vec<String>,
) -> CldrCacheResult<String> {
    let cache_root = cache_root.as_ref();
    let mut output = String::from("// generated by linguini-cldr-macros\n");
    output.push_str(
        "use linguini_cldr::{CompiledPluralCategory, CompiledPluralRules, CurrencyFormatData, DateFormatData, FormatWidths, NumberFormatData, PluralOperands};\n",
    );
    let mut plural_match = String::new();
    let mut plural_tables = String::new();
    let mut plural_functions = String::new();
    let mut number_match = String::new();
    let mut currency_match = String::new();
    let mut date_match = String::new();

    for locale in locales {
        let plurals = load_plural_rules_from_cache(cache_root, &locale)?;
        let numbers = load_number_formatting_from_cache(cache_root, &locale)?;
        let currency = load_currency_formatting_from_cache(cache_root, &locale)?;
        let dates = load_date_formatting_from_cache(cache_root, &locale)?;
        let name = const_name(&locale);

        plural_match.push_str(&format!(
            "{}=>Some(CompiledPluralRules{{locale:{},categories:PLURAL_CATEGORIES_{name}}}),",
            rust_string(&locale),
            rust_string(&locale)
        ));
        plural_tables.push_str(&format!(
            "const PLURAL_CATEGORIES_{name}:&[CompiledPluralCategory]=&["
        ));
        for category in &plurals.categories {
            let function = format!(
                "plural_{}_{}",
                name.to_ascii_lowercase(),
                const_name(&category.category).to_ascii_lowercase()
            );
            plural_tables.push_str(&format!(
                "CompiledPluralCategory{{category:{},matches:{function}}},",
                rust_string(&category.category)
            ));
            plural_functions.push_str(&plural_function(&function, &category.rule));
        }
        plural_tables.push_str("];");

        number_match.push_str(&format!(
            "{}=>Some(NumberFormatData{{locale:{}.to_owned(),decimal_symbol:{}.to_owned(),group_symbol:{}.to_owned(),decimal_pattern:{}.to_owned(),percent_pattern:{}.to_owned()}}),",
            rust_string(&locale),
            rust_string(&locale),
            rust_string(&numbers.decimal_symbol),
            rust_string(&numbers.group_symbol),
            rust_string(&numbers.decimal_pattern),
            rust_string(&numbers.percent_pattern)
        ));
        currency_match.push_str(&format!(
            "{}=>Some(CurrencyFormatData{{locale:{}.to_owned(),standard_pattern:{}.to_owned(),accounting_pattern:{}}}),",
            rust_string(&locale),
            rust_string(&locale),
            rust_string(&currency.standard_pattern),
            option_string(currency.accounting_pattern.as_deref())
        ));
        date_match.push_str(&format!(
            "{}=>Some(DateFormatData{{locale:{}.to_owned(),date_formats:{},time_formats:{},date_time_formats:{}}}),",
            rust_string(&locale),
            rust_string(&locale),
            widths(&dates.date_formats),
            widths(&dates.time_formats),
            widths(&dates.date_time_formats)
        ));
    }

    output.push_str(&format!(
        "pub fn compiled_plural_rules(locale:&str)->Option<CompiledPluralRules>{{match locale {{{plural_match}_=>None}}}}"
    ));
    output.push_str("fn integer_value(value:(f64,bool))->Option<u64>{if value.1&&value.0>=0.0{Some(value.0 as u64)}else{None}}");
    output.push_str(&plural_tables);
    output.push_str(&plural_functions);
    output.push_str(&format!(
        "pub fn compiled_number_formatting(locale:&str)->Option<NumberFormatData>{{match locale {{{number_match}_=>None}}}}"
    ));
    output.push_str(&format!(
        "pub fn compiled_currency_formatting(locale:&str)->Option<CurrencyFormatData>{{match locale {{{currency_match}_=>None}}}}"
    ));
    output.push_str(&format!(
        "pub fn compiled_date_formatting(locale:&str)->Option<DateFormatData>{{match locale {{{date_match}_=>None}}}}"
    ));
    Ok(output)
}

fn plural_function(name: &str, rule: &PluralRule) -> String {
    format!(
        "fn {name}(operands:&PluralOperands)->bool{{{}}}",
        plural_rule_to_rust(rule)
    )
}

fn plural_rule_to_rust(rule: &PluralRule) -> String {
    if rule.conditions.is_empty() {
        return "true".to_owned();
    }
    rule.conditions
        .iter()
        .map(condition_to_rust)
        .collect::<Vec<_>>()
        .join("||")
}

fn condition_to_rust(condition: &Condition) -> String {
    condition
        .relations
        .iter()
        .map(relation_to_rust)
        .collect::<Vec<_>>()
        .join("&&")
}

fn relation_to_rust(relation: &Relation) -> String {
    let expression = operand_expression_to_rust(&relation.expression);
    let ranges = ranges_to_rust(&relation.ranges.ranges, "value");
    match relation.operator {
        RelationOperator::Equal | RelationOperator::In => {
            format!("integer_value({expression}).is_some_and(|value|{ranges})")
        }
        RelationOperator::NotEqual | RelationOperator::NotIn => {
            format!("!integer_value({expression}).is_some_and(|value|{ranges})")
        }
        RelationOperator::Within => {
            let ranges = ranges_to_rust_float(&relation.ranges.ranges, "value");
            format!("{{let value=({expression}).0;value>=0.0&&{ranges}}}")
        }
        RelationOperator::NotWithin => {
            let ranges = ranges_to_rust_float(&relation.ranges.ranges, "value");
            format!("{{let value=({expression}).0;!(value>=0.0&&{ranges})}}")
        }
    }
}

fn operand_expression_to_rust(expression: &OperandExpression) -> String {
    let operand = match expression.operand {
        Operand::N => "(operands.n.parse::<f64>().unwrap_or(operands.i as f64),operands.v==0)",
        Operand::I => "(operands.i as f64,true)",
        Operand::V => "(operands.v as f64,true)",
        Operand::W => "(operands.w as f64,true)",
        Operand::F => "(operands.f as f64,true)",
        Operand::T => "(operands.t as f64,true)",
        Operand::C => "(operands.c as f64,true)",
        Operand::E => "(operands.e as f64,true)",
    };
    expression.modulo.map_or_else(
        || operand.to_owned(),
        |modulo| format!("{{let value={operand};(value.0%{modulo}f64,value.1)}}"),
    )
}

fn ranges_to_rust(ranges: &[Range], value: &str) -> String {
    ranges
        .iter()
        .map(|range| {
            if range.start == range.end {
                format!("{value}=={}", range.start)
            } else {
                format!("({value}>={}&{}<={})", range.start, value, range.end)
            }
        })
        .collect::<Vec<_>>()
        .join("||")
}

fn ranges_to_rust_float(ranges: &[Range], value: &str) -> String {
    ranges
        .iter()
        .map(|range| {
            if range.start == range.end {
                format!("{value}=={}f64", range.start)
            } else {
                format!("({value}>={}f64&&{value}<={}f64)", range.start, range.end)
            }
        })
        .collect::<Vec<_>>()
        .join("||")
}

fn const_name(locale: &str) -> String {
    locale
        .chars()
        .map(|ch| {
            if ch.is_ascii_alphanumeric() {
                ch.to_ascii_uppercase()
            } else {
                '_'
            }
        })
        .collect()
}

fn rust_string(value: &str) -> String {
    format!("{value:?}")
}

fn option_string(value: Option<&str>) -> String {
    value
        .map(|value| format!("Some({}.to_owned())", rust_string(value)))
        .unwrap_or_else(|| "None".to_owned())
}

fn widths(value: &FormatWidths) -> String {
    format!(
        "FormatWidths{{full:{}.to_owned(),long:{}.to_owned(),medium:{}.to_owned(),short:{}.to_owned()}}",
        rust_string(&value.full),
        rust_string(&value.long),
        rust_string(&value.medium),
        rust_string(&value.short)
    )
}
