use crate::{
    TypeScriptCodegenError, TypeScriptGeneratedFile, TypeScriptLocaleModule,
    TypeScriptProjectOptions, ValidatedTypeScriptProject,
};
use linguini_ir::{lower_locale, lower_schema};
use linguini_syntax::{parse_locale, parse_schema};
use std::fs;
use std::path::Path;

fn generate_project_files(
    schema: &linguini_ir::IrModule,
    locales: &[TypeScriptLocaleModule],
    options: &TypeScriptProjectOptions,
) -> Result<Vec<TypeScriptGeneratedFile>, TypeScriptCodegenError> {
    let project = ValidatedTypeScriptProject::try_new(schema, locales, options)?;
    crate::generate_typescript_project_files(&project)
}

fn project_options(base_locale: &str) -> TypeScriptProjectOptions {
    TypeScriptProjectOptions {
        base_locale: Some(base_locale.to_owned()),
        ..TypeScriptProjectOptions::default()
    }
}

#[test]
fn generated_module_snapshot_is_stable() {
    let schema = parse_schema(include_str!(
        "../../../tests/fixtures/golden/schema/shop.lgs"
    ))
    .expect("schema");
    let locale =
        parse_locale(include_str!("../../../tests/fixtures/golden/locale/ru.lgl")).expect("locale");

    let files = generate_project_files(
        &lower_schema(&schema),
        &[TypeScriptLocaleModule {
            locale: "ru".to_owned(),
            module: lower_locale(&locale),
        }],
        &TypeScriptProjectOptions {
            declaration: true,
            tree_shaking: false,
            included_messages: Vec::new(),
            base_locale: Some("ru".to_owned()),
            ..TypeScriptProjectOptions::default()
        },
    )
    .expect("project files");

    for file in files {
        if file.path == ".gitignore" {
            assert_eq!(file.contents, "# Generated by Linguini. Do not edit.\n*\n");
            continue;
        }
        let snapshot_path = format!("tests/fixtures/golden/snapshots/ts/{}", file.path);
        assert_snapshot(&snapshot_path, &file.contents);
    }
}

fn assert_snapshot(path: &str, snapshot: &str) {
    if std::env::var_os("LINGUINI_UPDATE_SNAPSHOTS").is_some() {
        let path = repo_root().join(path);
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent).expect("create snapshot dir");
        }
        fs::write(path, snapshot).expect("write snapshot");
    }

    let expected = fs::read_to_string(repo_root().join(path)).expect("read snapshot");
    assert_eq!(snapshot, expected);
}

fn repo_root() -> &'static Path {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(Path::parent)
        .expect("repo root")
}

#[test]
fn project_codegen_owns_multilocale_index_files() {
    use crate::{TypeScriptLocaleModule, TypeScriptProjectOptions};
    use linguini_ir::IrModule;

    let files = generate_project_files(
        &IrModule::default(),
        &[
            TypeScriptLocaleModule {
                locale: "en".to_owned(),
                module: IrModule::default(),
            },
            TypeScriptLocaleModule {
                locale: "ru".to_owned(),
                module: IrModule::default(),
            },
        ],
        &TypeScriptProjectOptions {
            declaration: true,
            tree_shaking: false,
            included_messages: Vec::new(),
            base_locale: Some("en".to_owned()),
            ..TypeScriptProjectOptions::default()
        },
    )
    .expect("project codegen");

    let index = files
        .iter()
        .find(|file| file.path == "index.ts")
        .expect("index.ts");
    assert!(index
        .contents
        .contains("import locale_en from \"./locales/en\";"));
    assert!(index
        .contents
        .contains("import locale_ru from \"./locales/ru\";"));
    assert!(index.contents.contains("ru: locale_ru"));
    assert!(index.contents.contains("from \"./locale\""));
    assert!(index
        .contents
        .contains("export type { Locale, TextDirection }"));
    let locale = files
        .iter()
        .find(|file| file.path == "locale.ts")
        .expect("locale.ts");
    assert!(locale
        .contents
        .contains("export const locales = [\"en\", \"ru\"]"));
    assert!(!locale.contents.contains("./locales/"));
    assert!(!locale.contents.contains("./messages"));
    let gitignore = files
        .iter()
        .find(|file| file.path == ".gitignore")
        .expect("generated gitignore");
    assert_eq!(
        gitignore.contents,
        "# Generated by Linguini. Do not edit.\n*\n"
    );
    assert_eq!(
        files
            .iter()
            .map(|file| file.path.as_str())
            .collect::<Vec<_>>(),
        [
            "shared.ts",
            "messages.ts",
            ".gitignore",
            "shared.d.ts",
            "messages.d.ts",
            "locales/en.ts",
            "locales/en.d.ts",
            "locales/ru.ts",
            "locales/ru.d.ts",
            "locale.ts",
            "locale.d.ts",
            "index.ts",
            "index.d.ts",
        ]
    );
    for forbidden in [
        ["coo", "kie"].concat(),
        ["localize", "Href"].concat(),
        ["Middle", "ware"].concat(),
    ] {
        assert!(!index.contents.contains(&forbidden));
    }
}

#[test]
fn project_codegen_can_omit_generated_gitignore() {
    use linguini_ir::IrModule;

    let files = generate_project_files(
        &IrModule::default(),
        &[TypeScriptLocaleModule {
            locale: "en".to_owned(),
            module: IrModule::default(),
        }],
        &TypeScriptProjectOptions {
            gitignore: false,
            ..project_options("en")
        },
    )
    .expect("project codegen");

    assert!(!files.iter().any(|file| file.path == ".gitignore"));
}

#[test]
fn project_codegen_always_emits_schema_owned_messages_type_module() {
    let schema = lower_schema(&parse_schema("title\n").expect("schema"));
    let locale = lower_locale(&parse_locale("title = Title\n").expect("locale"));

    let without_declarations = generate_project_files(
        &schema,
        &[TypeScriptLocaleModule {
            locale: "en".to_owned(),
            module: locale.clone(),
        }],
        &TypeScriptProjectOptions {
            declaration: false,
            ..project_options("en")
        },
    )
    .expect("source project");
    assert!(without_declarations
        .iter()
        .any(|file| file.path == "messages.ts"));
    assert!(!without_declarations
        .iter()
        .any(|file| file.path == "messages.d.ts"));

    let with_declarations = generate_project_files(
        &schema,
        &[TypeScriptLocaleModule {
            locale: "en".to_owned(),
            module: locale,
        }],
        &project_options("en"),
    )
    .expect("declaration project");
    assert!(with_declarations
        .iter()
        .any(|file| file.path == "messages.ts"));
    assert!(with_declarations
        .iter()
        .any(|file| file.path == "messages.d.ts"));
}

#[test]
fn project_codegen_emits_complete_recursive_schema_namespace_type() {
    let schema = lower_schema(
        &parse_schema(
            "/// Root docs\nroot {\n  /// Nested docs\n  nested {\n    /// Leaf docs\n    title\n    count(value: Number)\n  }\n  empty {}\n}\n",
        )
        .expect("schema"),
    );
    let locale = lower_locale(
        &parse_locale("root { nested { title = Title\ncount = Count {value} } }\n")
            .expect("locale"),
    );
    let files = generate_project_files(
        &schema,
        &[TypeScriptLocaleModule {
            locale: "en".to_owned(),
            module: locale,
        }],
        &project_options("en"),
    )
    .expect("project files");
    let messages = files
        .iter()
        .find(|file| file.path == "messages.ts")
        .expect("messages type module")
        .contents
        .clone();
    assert!(messages.contains("/** Root docs */"));
    assert!(messages.contains("/** Nested docs */"));
    assert!(messages.contains("/** Leaf docs */"));
    assert!(messages.contains("readonly title: string;"));
    assert!(messages.contains("readonly count: (value: number | bigint | string) => string;"));
    assert!(!messages.contains("empty"));
}

#[test]
fn project_codegen_escapes_recursive_namespace_docs_and_keys() {
    use linguini_ir::{
        IrGroup, IrMessage, IrModule, IrParameter, IrText, IrTextBlockMode, IrTextPart,
    };
    use linguini_syntax::Span;

    let names = [
        "top.class.foo-bar.deep.leaf-value",
        "top.class.foo-bar.deep.invoke",
    ];
    let schema = IrModule {
        messages: vec![
            IrMessage {
                name: names[0].to_owned(),
                docs: vec!["Value leaf\nsecond */ terminator".to_owned()],
                parameters: Vec::new(),
                body: None,
            },
            IrMessage {
                name: names[1].to_owned(),
                docs: vec!["Callable leaf".to_owned()],
                parameters: vec![IrParameter {
                    name: "count".to_owned(),
                    ty: "Number".to_owned(),
                }],
                body: None,
            },
        ],
        groups: vec![
            IrGroup {
                name: "top".to_owned(),
                docs: vec!["Top group\nline */ terminator".to_owned()],
                span: Span::new(0, 1),
            },
            IrGroup {
                name: "top.class".to_owned(),
                docs: vec!["Reserved class".to_owned()],
                span: Span::new(0, 1),
            },
            IrGroup {
                name: "top.class.foo-bar".to_owned(),
                docs: vec!["Unsafe namespace".to_owned()],
                span: Span::new(0, 1),
            },
            IrGroup {
                name: "top.class.foo-bar.deep".to_owned(),
                docs: vec!["Deep namespace".to_owned()],
                span: Span::new(0, 1),
            },
            IrGroup {
                name: "top.class.foo-bar.deep.empty".to_owned(),
                docs: vec!["Empty namespace".to_owned()],
                span: Span::new(0, 1),
            },
        ],
        ..IrModule::default()
    };
    let locale = IrModule {
        messages: names
            .iter()
            .map(|name| IrMessage {
                name: (*name).to_owned(),
                docs: Vec::new(),
                parameters: Vec::new(),
                body: Some(IrText {
                    parts: vec![IrTextPart::Text("ok".to_owned())],
                    mode: IrTextBlockMode::Inline,
                    span: Span::new(0, 2),
                }),
            })
            .collect(),
        ..IrModule::default()
    };
    let files = generate_project_files(
        &schema,
        &[TypeScriptLocaleModule {
            locale: "en".to_owned(),
            module: locale,
        }],
        &project_options("en"),
    )
    .expect("project files");
    let messages = files
        .iter()
        .find(|file| file.path == "messages.ts")
        .expect("messages type module")
        .contents
        .clone();

    assert_eq!(
        messages,
        r#"export type LinguiniMessages = {
  /** Top group
   * line * / terminator */
  readonly top: {
    /** Reserved class */
    readonly "class": {
      /** Unsafe namespace */
      readonly "foo-bar": {
        /** Deep namespace */
        readonly deep: {
          /** Value leaf
           * second * / terminator */
          readonly "leaf-value": string;
          /** Callable leaf */
          readonly invoke: (count: number | bigint | string) => string;
        };
      };
    };
  };
};
"#
    );
    assert!(!messages.contains("empty"));
}

#[test]
fn project_runtime_index_snapshot_is_stable() {
    use linguini_ir::IrModule;

    let files = generate_project_files(
        &IrModule::default(),
        &[
            TypeScriptLocaleModule {
                locale: "en".to_owned(),
                module: IrModule::default(),
            },
            TypeScriptLocaleModule {
                locale: "ru".to_owned(),
                module: IrModule::default(),
            },
        ],
        &TypeScriptProjectOptions {
            declaration: true,
            tree_shaking: false,
            included_messages: Vec::new(),
            base_locale: Some("en".to_owned()),
            ..TypeScriptProjectOptions::default()
        },
    )
    .expect("project codegen");

    let index = files
        .iter()
        .find(|file| file.path == "index.ts")
        .expect("index.ts");
    assert_snapshot(
        "tests/fixtures/golden/snapshots/ts-runtime/index.ts",
        &index.contents,
    );
}

#[test]
fn project_codegen_filters_messages_in_tree_shaking_mode() {
    use crate::{TypeScriptLocaleModule, TypeScriptProjectOptions};

    let schema = lower_schema(&parse_schema("keep\ndrop\ngroup { label help }\n").expect("schema"));
    let locale = lower_locale(
        &parse_locale("keep = Keep\ndrop = Drop\ngroup {\n  label = Label\n  help = Help\n}\n")
            .expect("locale"),
    );

    let files = generate_project_files(
        &schema,
        &[TypeScriptLocaleModule {
            locale: "en".to_owned(),
            module: locale.clone(),
        }],
        &TypeScriptProjectOptions {
            declaration: true,
            tree_shaking: true,
            included_messages: vec!["keep".to_owned(), "group.label".to_owned()],
            base_locale: Some("en".to_owned()),
            ..TypeScriptProjectOptions::default()
        },
    )
    .expect("project codegen");

    let locale_module = files
        .iter()
        .find(|file| file.path == "locales/en.ts")
        .expect("locale module");
    let messages_type = files
        .iter()
        .find(|file| file.path == "messages.ts")
        .expect("messages type module");
    assert!(messages_type.contents.contains("readonly keep: string;"));
    assert!(messages_type.contents.contains("readonly group:"));
    assert!(messages_type.contents.contains("readonly label: string;"));
    assert!(!messages_type.contents.contains("readonly drop: string;"));
    assert!(!messages_type.contents.contains("readonly help: string;"));
    assert!(locale_module
        .contents
        .contains("export const keep = \"Keep\";"));
    assert!(!locale_module.contents.contains("export const drop"));
    assert!(locale_module
        .contents
        .contains("import { group } from \"./en/group\";"));

    let group_module = files
        .iter()
        .find(|file| file.path == "locales/en/group.ts")
        .expect("group locale module");
    assert!(group_module.contents.contains("label: \"Label\""));
    assert!(!group_module.contents.contains("help: \"Help\""));
    assert!(!locale_module.contents.contains("help: \"Help\""));

    let full_files = generate_project_files(
        &schema,
        &[TypeScriptLocaleModule {
            locale: "en".to_owned(),
            module: locale,
        }],
        &TypeScriptProjectOptions {
            declaration: true,
            tree_shaking: false,
            base_locale: Some("en".to_owned()),
            ..TypeScriptProjectOptions::default()
        },
    )
    .expect("full project codegen");
    for path in ["locale.ts", "locale.d.ts"] {
        let selected = files.iter().find(|file| file.path == path).expect(path);
        let full = full_files
            .iter()
            .find(|file| file.path == path)
            .expect(path);
        assert_eq!(selected.contents, full.contents);
    }
}

#[test]
fn project_codegen_emits_parameterless_messages_as_values() {
    let schema = lower_schema(
        &parse_schema(
            r#"
title
account {
  label
  personalized(name: String)
}
"#,
        )
        .expect("schema"),
    );
    let locale = lower_locale(
        &parse_locale(
            r#"
let product = Linguini
title = Welcome to {product}
account {
  label = Your {product} account
  personalized = Hello {name}
}
"#,
        )
        .expect("locale"),
    );

    let files = generate_project_files(
        &schema,
        &[TypeScriptLocaleModule {
            locale: "en".to_owned(),
            module: locale,
        }],
        &TypeScriptProjectOptions {
            declaration: true,
            ..project_options("en")
        },
    )
    .expect("project codegen");

    let locale_module = files
        .iter()
        .find(|file| file.path == "locales/en.ts")
        .expect("locale module");
    assert!(locale_module
        .contents
        .contains("export const title = \"Welcome to \" + String(product);"));
    assert!(!locale_module.contents.contains("function title("));

    let account_module = files
        .iter()
        .find(|file| file.path == "locales/en/account.ts")
        .expect("account locale module");
    assert!(account_module
        .contents
        .contains("label: \"Your \" + String(product) + \" account\","));
    assert!(!account_module.contents.contains("label: () =>"));
    assert!(account_module
        .contents
        .contains("personalized: (name: string) => \"Hello \" + String(name),"));

    let locale_declaration = files
        .iter()
        .find(|file| file.path == "locales/en.d.ts")
        .expect("locale declaration");
    assert!(locale_declaration
        .contents
        .contains("export declare const title: string;"));
    assert!(!locale_declaration.contents.contains("function title("));
    let account_declaration = files
        .iter()
        .find(|file| file.path == "locales/en/account.d.ts")
        .expect("account locale declaration");
    assert!(account_declaration
        .contents
        .contains("readonly label: string;"));
    assert!(account_declaration
        .contents
        .contains("readonly personalized: (name: string) => string;"));
}

#[test]
fn project_codegen_applies_schema_formatter_aliases() {
    let schema = lower_schema(
        &parse_schema(
            r#"
type Price = Number @currency(code = "EUR")
type ShortDate = Date @date(style = "short")
total(price: Price, created: ShortDate)
plain(price: Price)
"#,
        )
        .expect("schema"),
    );
    let locale = lower_locale(
        &parse_locale(
            r#"
total = Total {price} on {created}
plain = Raw {price @number}
"#,
        )
        .expect("locale"),
    );

    let files = generate_project_files(
        &schema,
        &[TypeScriptLocaleModule {
            locale: "en".to_owned(),
            module: locale,
        }],
        &project_options("en"),
    )
    .expect("project codegen");

    let locale_module = files
        .iter()
        .find(|file| file.path == "locales/en.ts")
        .expect("locale module");
    assert!(!locale_module.contents.contains("FORMATTER_DATA"));
    assert!(!locale_module.contents.contains("GeneratedNumberPattern"));
    assert!(!locale_module.contents.contains("Intl.DateTimeFormat"));
    assert!(!locale_module.contents.contains("replace(/[#0"));
    assert!(locale_module.contents.contains("function formatCurrency("));
    assert!(locale_module
        .contents
        .contains("formatCurrency(price, 2, 0, { code: \"EUR\" })"));
    assert!(locale_module.contents.contains("function formatDate("));
    assert!(locale_module
        .contents
        .contains("const date = coerceDate(value);"));
    assert!(locale_module
        .contents
        .contains("function coerceDate(value: Date | number | string): Date"));
    assert!(locale_module
        .contents
        .contains("formatDate(created, { style: \"short\" })"));
    let shared_module = files
        .iter()
        .find(|file| file.path == "shared.ts")
        .expect("shared module");
    assert!(shared_module
        .contents
        .contains("export type ShortDate = Date | number | string;"));
    assert!(locale_module
        .contents
        .contains("export function plain(price: Price): string"));
    assert!(locale_module.contents.contains("formatNumber(price)"));
}

#[test]
fn project_codegen_applies_cldr_currency_minor_units() {
    let schema = lower_schema(
        &parse_schema("yen(value: Decimal)\ndinar(value: Decimal)\nuf(value: Decimal)\n")
            .expect("schema"),
    );
    let locale = lower_locale(
        &parse_locale(
            "yen = {value @currency(code = \"JPY\")}\n\
dinar = {value @currency(code = \"KWD\")}\n\
uf = {value @currency(code = \"CLF\")}\n",
        )
        .expect("locale"),
    );

    let files = generate_project_files(
        &schema,
        &[TypeScriptLocaleModule {
            locale: "en".to_owned(),
            module: locale,
        }],
        &project_options("en"),
    )
    .expect("project codegen");
    let module = files
        .iter()
        .find(|file| file.path == "locales/en.ts")
        .expect("locale module");

    assert!(module
        .contents
        .contains("formatCurrency(value, 0, 0, { code: \"JPY\" })"));
    assert!(module
        .contents
        .contains("formatCurrency(value, 3, 0, { code: \"KWD\" })"));
    assert!(module
        .contents
        .contains("formatCurrency(value, 4, 0, { code: \"CLF\" })"));
}

#[test]
fn project_validation_rejects_missing_required_formatter_data() {
    let schema = lower_schema(&parse_schema("dated(value: Date)\n").expect("schema"));
    let locale = lower_locale(&parse_locale("dated = {value}\n").expect("locale"));

    let error = ValidatedTypeScriptProject::try_new(
        &schema,
        &[TypeScriptLocaleModule {
            locale: "haw".to_owned(),
            module: locale,
        }],
        &project_options("haw"),
    )
    .expect_err("Hawaiian date data is intentionally absent from the compiled CLDR artifact");

    assert_eq!(
        error,
        TypeScriptCodegenError::MissingDateFormatting {
            locale: "haw".to_owned(),
        }
    );
}

#[test]
fn project_codegen_applies_primitive_schema_formatters() {
    let schema = lower_schema(
        &parse_schema("summary(count: Number, amount: Decimal, created: Date)\n").expect("schema"),
    );
    let locale =
        lower_locale(&parse_locale("summary = {count} / {amount} / {created}\n").expect("locale"));

    let files = generate_project_files(
        &schema,
        &[TypeScriptLocaleModule {
            locale: "en".to_owned(),
            module: locale,
        }],
        &project_options("en"),
    )
    .expect("project codegen");

    let locale_module = files
        .iter()
        .find(|file| file.path == "locales/en.ts")
        .expect("locale module");
    assert!(locale_module.contents.contains("formatNumber(count)"));
    assert!(locale_module.contents.contains("formatNumber(amount)"));
    assert!(locale_module.contents.contains("formatDate(created"));
}

#[test]
fn project_codegen_emits_inline_function_dispatch_with_captured_values() {
    let schema = lower_schema(
        &parse_schema(
            "enum Gender { masculine, feminine, other }\ngreeting(name: String, gender: Gender)\n",
        )
        .expect("schema"),
    );
    let locale = lower_locale(
        &parse_locale(
            "greeting = Hello {fn(gender) {\n\
               masculine => dear {name}\n\
               feminine => kind {name}\n\
               _ => friend {name}\n\
             }}!\n",
        )
        .expect("locale"),
    );

    let files = generate_project_files(
        &schema,
        &[TypeScriptLocaleModule {
            locale: "en".to_owned(),
            module: locale,
        }],
        &project_options("en"),
    )
    .expect("project codegen");
    let module = files
        .iter()
        .find(|file| file.path == "locales/en.ts")
        .expect("locale module");

    assert!(module
        .contents
        .contains("import { selectBranch } from \"../shared\";"));
    assert!(module.contents.contains(
        "selectBranch(String(__lgl_inline_selector_0), { masculine: (): string => \"dear \" + String(name), feminine: (): string => \"kind \" + String(name), _: (): string => \"friend \" + String(name) })()"
    ));
    assert!(module.contents.contains(") => selectBranch"));
    assert!(module.contents.contains(")(gender)"));
}

#[test]
fn project_codegen_normalizes_inferred_plural_inline_selectors() {
    let schema = lower_schema(&parse_schema("summary(count: Number)\n").expect("schema"));
    let locale = lower_locale(
        &parse_locale(
            "fn Render(category: Plural) {\n  _ => {fn(category) {\n    one => one\n    _ => other\n  }}\n}\nsummary = {Render(count)}\n",
        )
        .expect("locale"),
    );

    let files = generate_project_files(
        &schema,
        &[TypeScriptLocaleModule {
            locale: "en".to_owned(),
            module: locale,
        }],
        &project_options("en"),
    )
    .expect("project codegen");
    let module = files
        .iter()
        .find(|file| file.path == "locales/en.ts")
        .expect("locale module");

    assert!(module.contents.contains(
        "selectBranch(pluralEn(__lgl_inline_selector_0), { one: (): string => \"one\", _: (): string => \"other\" })()"
    ));
    assert!(module.contents.contains(")(category)"));
}

#[test]
fn project_codegen_keeps_form_parameter_types_in_inline_branches() {
    let schema = lower_schema(
        &parse_schema("enum Fruit { apple }\nsummary(fruit: Fruit, count: Number)\n")
            .expect("schema"),
    );
    let locale = lower_locale(
        &parse_locale(
            "impl Fruit {\n  apple {\n    form label(count: Plural) {\n      one => {fn(count) {\n        one => one\n        _ => other\n      }}\n      _ => fallback\n    }\n  }\n}\nsummary = {fruit.label(count)}\n",
        )
        .expect("locale"),
    );

    let files = generate_project_files(
        &schema,
        &[TypeScriptLocaleModule {
            locale: "en".to_owned(),
            module: locale,
        }],
        &project_options("en"),
    )
    .expect("project codegen");
    let module = files
        .iter()
        .find(|file| file.path == "locales/en.ts")
        .expect("locale module");

    assert!(module
        .contents
        .contains("label: (count: number | bigint | string) => selectBranch(pluralEn(count),"));
    assert!(module
        .contents
        .contains("selectBranch(pluralEn(__lgl_inline_selector_0),"));
}

#[test]
fn project_codegen_internal_parameters_do_not_collide_with_source_names() {
    let schema = lower_schema(
        &parse_schema("enum Tone { formal, casual }\nsummary(tone: Tone, value: String)\n")
            .expect("schema"),
    );
    let locale = lower_locale(
        &parse_locale(
            "fn Wrap(Tone, __lgl_p0: String) {\n  formal => {__lgl_p0}\n  _ => {__lgl_p0}\n}\nsummary = {fn(tone, __lgl_inline_selector_0: Wrap(tone, value)) {\n  formal => {__lgl_inline_selector_0}\n  _ => {__lgl_inline_selector_0}\n}}\n",
        )
        .expect("locale"),
    );

    let files = generate_project_files(
        &schema,
        &[TypeScriptLocaleModule {
            locale: "en".to_owned(),
            module: locale,
        }],
        &project_options("en"),
    )
    .expect("project codegen");
    let module = files
        .iter()
        .find(|file| file.path == "locales/en.ts")
        .expect("locale module");

    assert!(!module
        .contents
        .contains("function Wrap(__lgl_p0: Tone, __lgl_p0:"));
    assert!(!module
        .contents
        .contains("(__lgl_inline_selector_0, __lgl_inline_selector_0)"));
    assert!(module.contents.contains("__lgl_name_"));
}

#[test]
fn project_codegen_emits_nested_anonymous_function_dispatch() {
    let schema = lower_schema(
        &parse_schema(
            "enum Gender { masculine, feminine, other }\nsummary(gender: Gender, count: Number, name: String)\n",
        )
        .expect("schema"),
    );
    let locale = lower_locale(
        &parse_locale(
            "summary = {fn(gender, Plural(count)) {\n\
               masculine {\n\
                 one => One {name}\n\
                 other => Many {name}\n\
               }\n\
               feminine {\n\
                 one => One {name}\n\
                 other => Many {name}\n\
               }\n\
               other {\n\
                 one => One {name}\n\
                 other => Many {name}\n\
               }\n\
             }}\n",
        )
        .expect("locale"),
    );

    let files = generate_project_files(
        &schema,
        &[TypeScriptLocaleModule {
            locale: "en".to_owned(),
            module: locale,
        }],
        &project_options("en"),
    )
    .expect("project codegen");
    let module = files
        .iter()
        .find(|file| file.path == "locales/en.ts")
        .expect("locale module");

    assert!(module
        .contents
        .contains("selectBranch(String(__lgl_inline_selector_0),"));
    assert!(module
        .contents
        .contains("selectBranch(String(__lgl_inline_selector_1),"));
    assert!(module.contents.contains(")(gender, pluralEn(count))"));
    assert!(module
        .contents
        .contains("masculine: (): string => selectBranch"));
    assert!(module.contents.contains("\"One \" + String(name)"));
}

#[test]
fn project_codegen_uses_a_data_property_for_proto_inline_branch() {
    let schema = lower_schema(
        &parse_schema("enum Key { __proto__, other }\nlabel(key: Key)\n").expect("schema"),
    );
    let locale = lower_locale(
        &parse_locale("label = {fn(key) {\n  __proto__ => Safe\n  _ => Fallback\n}}\n")
            .expect("locale"),
    );

    let files = generate_project_files(
        &schema,
        &[TypeScriptLocaleModule {
            locale: "en".to_owned(),
            module: locale,
        }],
        &project_options("en"),
    )
    .expect("project codegen");
    let module = files
        .iter()
        .find(|file| file.path == "locales/en.ts")
        .expect("locale module");

    assert!(module
        .contents
        .contains("[\"__proto__\"]: (): string => \"Safe\""));
}

#[test]
fn project_codegen_named_and_anonymous_functions_share_dispatch_semantics() {
    let schema = lower_schema(
        &parse_schema(
            "enum Tone { __proto__, formal, casual }\n\
             named(name: String, tone: Tone, count: Number)\n\
             anonymous(name: String, tone: Tone, count: Number)\n",
        )
        .expect("schema"),
    );
    let locale = lower_locale(
        &parse_locale(
            "fn Echo(value: String) {\n\
               _ => {value}\n\
             }\n\
             fn Choose(Tone, Plural, name: String) {\n\
               __proto__ {\n\
                 one => One {name}\n\
                 other => Many {name}\n\
               }\n\
               formal {\n\
                 one => One {name}\n\
                 other => Many {name}\n\
               }\n\
               casual {\n\
                 one => One {name}\n\
                 other => Many {name}\n\
               }\n\
             }\n\
             named = {Choose(tone, count, name)}\n\
             anonymous = {fn(tone, Plural(count), copy: Echo(name)) {\n\
               __proto__ {\n\
                 one => One {copy}\n\
                 other => Many {name}\n\
               }\n\
               formal {\n\
                 one => One {copy}\n\
                 other => Many {name}\n\
               }\n\
               casual {\n\
                 one => One {copy}\n\
                 other => Many {name}\n\
               }\n\
             }}\n",
        )
        .expect("locale"),
    );

    let files = generate_project_files(
        &schema,
        &[TypeScriptLocaleModule {
            locale: "en".to_owned(),
            module: locale,
        }],
        &project_options("en"),
    )
    .expect("project codegen");
    let module = files
        .iter()
        .find(|file| file.path == "locales/en.ts")
        .expect("locale module");

    let signature =
        "(name: string, tone: Tone, count: number | bigint | string): string {\n  return ";
    let named_dispatch = module
        .contents
        .split_once("function Choose(__lgl_p0: Tone, __lgl_p1: number | bigint | string, name: string): string {\n  return ")
        .expect("named function dispatch")
        .1
        .split_once(";\n}")
        .expect("named function end")
        .0;
    let anonymous_body = module
        .contents
        .split_once(&format!("export function anonymous{signature}"))
        .expect("anonymous message body")
        .1
        .split_once(";\n}")
        .expect("anonymous message end")
        .0;
    assert!(named_dispatch.starts_with("selectBranch(String(__lgl_p0),"));
    assert!(
        named_dispatch.contains("[\"__proto__\"]: (): string => selectBranch(pluralEn(__lgl_p1),")
    );
    assert!(named_dispatch.contains("one: (): string => \"One \" + String(name)"));
    assert!(named_dispatch.contains("other: (): string => \"Many \" + String(name)"));
    assert!(named_dispatch.ends_with(")()"));
    assert!(anonymous_body.contains(
        "((__lgl_inline_selector_0, __lgl_inline_selector_1, copy) => selectBranch(String(__lgl_inline_selector_0),"
    ));
    assert!(anonymous_body
        .contains("[\"__proto__\"]: (): string => selectBranch(String(__lgl_inline_selector_1),"));
    assert!(anonymous_body.contains("one: (): string => \"One \" + String(copy)"));
    assert!(anonymous_body.contains(")(tone, pluralEn(count), Echo(name))"));
}

#[test]
fn project_codegen_types_numeric_and_locale_enum_function_parameters() {
    let schema = lower_schema(
        &parse_schema(
            "enum Fruit { apple }\ndelivery(label: String, count: Number, fruit: Fruit)\n",
        )
        .expect("schema"),
    );
    let locale = lower_locale(
        &parse_locale(
            "enum Gender { male, other }\n\
             impl Fruit { apple { Gender = male } }\n\
             fn choose(Number, Gender, value: String) {\n\
               _ {\n\
                 male => {value}\n\
                 other => {value}\n\
               }\n\
             }\n\
             delivery = {choose(count, fruit.Gender, label)}\n",
        )
        .expect("locale"),
    );

    let files = generate_project_files(
        &schema,
        &[TypeScriptLocaleModule {
            locale: "en".to_owned(),
            module: locale,
        }],
        &project_options("en"),
    )
    .expect("project codegen");
    let module = files
        .iter()
        .find(|file| file.path == "locales/en.ts")
        .expect("locale module");

    assert!(module
        .contents
        .contains("type Gender = \"male\" | \"other\";"));
    assert!(module.contents.contains(
        "function choose(__lgl_p0: number | bigint | string, __lgl_p1: Gender, value: string): string"
    ));
}

#[test]
fn project_codegen_normalizes_a_numeric_value_for_a_plural_form() {
    let schema = lower_schema(
        &parse_schema("enum Tone { formal, casual }\ngreeting(tone: Tone, count: Number)\n")
            .expect("schema"),
    );
    let locale = lower_locale(
        &parse_locale(
            "form Greeting(Tone, Plural) {\n\
               formal { one => Formal one\nother => Formal many }\n\
               casual { one => Casual one\nother => Casual many }\n\
             }\n\
             greeting = {Greeting(tone, count)}\n",
        )
        .expect("locale"),
    );

    let files = generate_project_files(
        &schema,
        &[TypeScriptLocaleModule {
            locale: "en".to_owned(),
            module: locale,
        }],
        &project_options("en"),
    )
    .expect("project codegen");
    let module = files
        .iter()
        .find(|file| file.path == "locales/en.ts")
        .expect("locale module");

    assert!(module.contents.contains("Greeting(tone, count)"));
}

#[test]
fn project_codegen_emits_callable_form_variants_with_attributes() {
    let schema = lower_schema(
        &parse_schema("enum Fruit { apple }\nlabel(fruit: Fruit, count: Number)\n")
            .expect("schema"),
    );
    let locale = lower_locale(
        &parse_locale(
            r#"
impl Fruit {
  apple {
    one => apple
    _ => apples
    label = Apple
  }
}
label = {fruit(count)}: {fruit.label}
"#,
        )
        .expect("locale"),
    );

    let locale_module =
        crate::module::generate_unvalidated_typescript_module_for_test(&schema, &locale, "en");
    assert!(locale_module.contains(
        "apple: Object.assign((value: number | bigint | string) => \
selectBranch(pluralEn(value), { one: \"apple\", _: \"apples\" }), { label: \"Apple\" })"
    ));
    assert!(locale_module.contains(
        "return String(__lgl_form_4672756974[fruit](count)) + \": \" + \
String(__lgl_form_4672756974[fruit].label);"
    ));
}

#[test]
fn project_codegen_preserves_every_multi_key_branch() {
    let schema = lower_schema(
        &parse_schema("enum Fruit { apple }\nlabel(fruit: Fruit, count: Number)\n")
            .expect("schema"),
    );
    let locale = lower_locale(
        &parse_locale(
            r#"
impl Fruit {
  apple {
    one, few, many => apples
    _ => fruit
  }
}
label = {fruit(count)}
"#,
        )
        .expect("locale"),
    );

    let locale_module =
        crate::module::generate_unvalidated_typescript_module_for_test(&schema, &locale, "en");
    assert!(locale_module.contains(
        "apple: (value: number | bigint | string) => selectBranch(pluralEn(value), \
{ one: \"apples\", few: \"apples\", many: \"apples\", _: \"fruit\" })"
    ));
}

#[test]
fn project_validation_rejects_an_empty_locale_set() {
    let error = ValidatedTypeScriptProject::try_new(
        &linguini_ir::IrModule::default(),
        &[],
        &project_options("en"),
    )
    .expect_err("an empty locale set must be rejected");

    assert_eq!(error, TypeScriptCodegenError::EmptyLocaleSet);
}

#[test]
fn project_validation_rejects_duplicate_and_case_folded_locales() {
    use linguini_ir::IrModule;

    for conflicting_locale in ["en", "EN"] {
        let error = ValidatedTypeScriptProject::try_new(
            &IrModule::default(),
            &[
                TypeScriptLocaleModule {
                    locale: "en".to_owned(),
                    module: IrModule::default(),
                },
                TypeScriptLocaleModule {
                    locale: conflicting_locale.to_owned(),
                    module: IrModule::default(),
                },
            ],
            &project_options("en"),
        )
        .expect_err("case-folded locale collisions must be rejected");

        assert_eq!(
            error,
            TypeScriptCodegenError::DuplicateLocale {
                locale: conflicting_locale.to_owned(),
                conflicts_with: "en".to_owned(),
            }
        );
    }
}

#[test]
fn project_validation_rejects_unsafe_locale_filenames() {
    use linguini_ir::IrModule;

    for locale in [
        "",
        ".",
        "..",
        "../en",
        "en/us",
        r"en\us",
        "name.",
        "name ",
        "a:b",
        "CON",
        "LPT9",
        "日本語",
    ] {
        let error = ValidatedTypeScriptProject::try_new(
            &IrModule::default(),
            &[TypeScriptLocaleModule {
                locale: locale.to_owned(),
                module: IrModule::default(),
            }],
            &project_options(locale),
        )
        .expect_err("unsafe locale filename must be rejected");

        assert!(
            matches!(
                error,
                TypeScriptCodegenError::InvalidLocalePathComponent {
                    locale: ref rejected,
                    ..
                } if rejected == locale
            ),
            "{locale:?}: {error:?}"
        );
    }
}

#[test]
fn project_validation_rejects_namespace_filenames_beyond_portable_limits() {
    use linguini_ir::{IrMessage, IrModule};

    let namespace = "x".repeat(241);
    let schema = IrModule {
        messages: vec![IrMessage {
            name: format!("{namespace}.title"),
            docs: Vec::new(),
            parameters: Vec::new(),
            body: None,
        }],
        ..IrModule::default()
    };
    let error = ValidatedTypeScriptProject::try_new(
        &schema,
        &[TypeScriptLocaleModule {
            locale: "en".to_owned(),
            module: IrModule::default(),
        }],
        &project_options("en"),
    )
    .expect_err("oversized namespace filename must be rejected");

    assert_eq!(
        error,
        TypeScriptCodegenError::InvalidNamespacePathComponent {
            namespace,
            reason: "component exceeds the portable 240-byte limit",
        }
    );
}

#[test]
fn project_codegen_encodes_unsafe_namespace_filenames_and_imports() {
    use linguini_ir::{IrMessage, IrModule, IrText, IrTextBlockMode, IrTextPart};
    use linguini_syntax::Span;

    let names = [
        "admin/path.ready",
        "CON.status",
        "日本語.title",
        "__lgl_path_434F4E.literal",
    ];
    let schema = IrModule {
        messages: names
            .iter()
            .map(|name| IrMessage {
                name: (*name).to_owned(),
                docs: Vec::new(),
                parameters: Vec::new(),
                body: None,
            })
            .collect(),
        ..IrModule::default()
    };
    let locale = IrModule {
        messages: names
            .iter()
            .map(|name| IrMessage {
                name: (*name).to_owned(),
                docs: Vec::new(),
                parameters: Vec::new(),
                body: Some(IrText {
                    parts: vec![IrTextPart::Text("ok".to_owned())],
                    mode: IrTextBlockMode::Inline,
                    span: Span::new(0, 2),
                }),
            })
            .collect(),
        ..IrModule::default()
    };

    let files = generate_project_files(
        &schema,
        &[TypeScriptLocaleModule {
            locale: "en".to_owned(),
            module: locale,
        }],
        &project_options("en"),
    )
    .expect("unsafe logical namespaces are encoded");
    let paths = files
        .iter()
        .map(|file| file.path.as_str())
        .collect::<Vec<_>>();
    for expected in [
        "locales/en/__lgl_path_61646D696E2F70617468.ts",
        "locales/en/__lgl_path_434F4E.ts",
        "locales/en/__lgl_path_E697A5E69CACE8AA9E.ts",
        "locales/en/__lgl_path_5F5F6C676C5F706174685F343334463445.ts",
    ] {
        assert!(paths.contains(&expected), "missing {expected}: {paths:#?}");
    }
    assert!(paths
        .iter()
        .all(|path| !path.contains("admin/path") && !path.contains("日本語")));

    let barrel = files
        .iter()
        .find(|file| file.path == "locales/en.ts")
        .expect("locale barrel");
    assert!(barrel
        .contents
        .contains("from \"./en/__lgl_path_61646D696E2F70617468\";"));
    assert!(barrel.contents.contains("from \"./en/__lgl_path_434F4E\";"));

    let declarations = files
        .iter()
        .find(|file| file.path == "locales/en.d.ts")
        .expect("locale declaration barrel");
    assert!(declarations
        .contents
        .contains("from \"./en/__lgl_path_61646D696E2F70617468\";"));
}

#[test]
fn project_validation_rejects_case_insensitive_namespace_file_collisions() {
    use linguini_ir::{IrMessage, IrModule, IrText, IrTextBlockMode, IrTextPart};
    use linguini_syntax::Span;

    let schema = IrModule {
        messages: ["Shop.title", "shop.subtitle"]
            .into_iter()
            .map(|name| IrMessage {
                name: name.to_owned(),
                docs: Vec::new(),
                parameters: Vec::new(),
                body: None,
            })
            .collect(),
        ..IrModule::default()
    };
    let locale = IrModule {
        messages: ["Shop.title", "shop.subtitle"]
            .into_iter()
            .map(|name| IrMessage {
                name: name.to_owned(),
                docs: Vec::new(),
                parameters: Vec::new(),
                body: Some(IrText {
                    parts: vec![IrTextPart::Text("ok".to_owned())],
                    mode: IrTextBlockMode::Inline,
                    span: Span::new(0, 2),
                }),
            })
            .collect(),
        ..IrModule::default()
    };

    let error = generate_project_files(
        &schema,
        &[TypeScriptLocaleModule {
            locale: "en".to_owned(),
            module: locale,
        }],
        &project_options("en"),
    )
    .expect_err("case-insensitive namespace collision must be rejected");

    assert_eq!(
        error,
        TypeScriptCodegenError::OutputPathCollision {
            path: "locales/en/shop.ts".to_owned(),
            conflicts_with: "locales/en/Shop.ts (namespace `Shop`)".to_owned(),
        }
    );
}

#[test]
fn project_validation_requires_an_explicit_base_locale() {
    use linguini_ir::IrModule;

    let error = ValidatedTypeScriptProject::try_new(
        &IrModule::default(),
        &[TypeScriptLocaleModule {
            locale: "en".to_owned(),
            module: IrModule::default(),
        }],
        &TypeScriptProjectOptions::default(),
    )
    .expect_err("a missing base locale must not fall back to the first locale");

    assert_eq!(error, TypeScriptCodegenError::MissingBaseLocale);
}

#[test]
fn project_validation_rejects_an_unknown_base_locale() {
    use linguini_ir::IrModule;

    let error = ValidatedTypeScriptProject::try_new(
        &IrModule::default(),
        &[TypeScriptLocaleModule {
            locale: "en".to_owned(),
            module: IrModule::default(),
        }],
        &project_options("fr"),
    )
    .expect_err("an unknown base locale must not fall back to the first locale");

    assert_eq!(
        error,
        TypeScriptCodegenError::UnknownBaseLocale {
            base_locale: "fr".to_owned(),
        }
    );
}

#[test]
fn project_validation_rejects_unknown_included_messages() {
    use linguini_ir::IrModule;

    let schema = lower_schema(&parse_schema("known\naccount { title }\n").expect("schema"));
    let options = TypeScriptProjectOptions {
        tree_shaking: true,
        included_messages: vec!["missing".to_owned()],
        ..project_options("en")
    };
    let error = ValidatedTypeScriptProject::try_new(
        &schema,
        &[TypeScriptLocaleModule {
            locale: "en".to_owned(),
            module: IrModule::default(),
        }],
        &options,
    )
    .expect_err("unknown tree-shaking roots must be rejected");

    assert_eq!(
        error,
        TypeScriptCodegenError::UnknownIncludedMessage {
            message: "missing".to_owned(),
        }
    );
}

#[test]
fn project_validation_rejects_locales_without_cldr_text_direction() {
    use linguini_ir::IrModule;

    let error = ValidatedTypeScriptProject::try_new(
        &IrModule::default(),
        &[TypeScriptLocaleModule {
            locale: "zz-ZZ".to_owned(),
            module: IrModule::default(),
        }],
        &project_options("zz-ZZ"),
    )
    .expect_err("an unknown text direction must not be coerced to LTR");

    assert_eq!(
        error,
        TypeScriptCodegenError::MissingTextDirection {
            locale: "zz-ZZ".to_owned(),
        }
    );
}

#[test]
fn project_validation_rejects_formatter_alias_cycles() {
    let schema = lower_schema(
        &parse_schema("type First = Second\ntype Second = First\nlabel(value: First)\n")
            .expect("schema"),
    );
    let locale = lower_locale(&parse_locale("label = {value}\n").expect("locale implementation"));

    let error = ValidatedTypeScriptProject::try_new(
        &schema,
        &[TypeScriptLocaleModule {
            locale: "en".to_owned(),
            module: locale,
        }],
        &project_options("en"),
    )
    .expect_err("cyclic aliases must be rejected before codegen");

    let TypeScriptCodegenError::InvalidIr { errors, .. } = error else {
        panic!("expected invalid IR error");
    };
    assert!(errors.iter().any(|error| error.code == "IR008"));
}

#[test]
fn project_validation_rejects_unresolved_locale_messages() {
    let schema = lower_schema(&parse_schema("known\n").expect("schema"));
    let locale = lower_locale(&parse_locale("unknown = Unknown\n").expect("locale"));

    let error = ValidatedTypeScriptProject::try_new(
        &schema,
        &[TypeScriptLocaleModule {
            locale: "en".to_owned(),
            module: locale,
        }],
        &project_options("en"),
    )
    .expect_err("unresolved locale message must be rejected");

    let TypeScriptCodegenError::InvalidIr { scope, errors } = error else {
        panic!("expected invalid IR error");
    };
    assert_eq!(scope, "locale `en`");
    assert!(errors.iter().any(|error| error.code == "IR010"));
}

#[test]
fn project_validation_checks_fallback_composed_modules() {
    let schema = lower_schema(&parse_schema("greeting\n").expect("schema"));
    let base = lower_locale(
        &parse_locale(
            r#"
let name = Base
fn Wrap(value: String) {
  _ => {value}
}
greeting = {Wrap(name)}
"#,
        )
        .expect("base locale"),
    );
    let regional = lower_locale(
        &parse_locale(
            r#"
fn Wrap(value: Number) {
  _ => {value}
}
"#,
        )
        .expect("regional locale"),
    );
    linguini_ir::validate_ir(&schema, &base).expect("base locale is independently valid");
    linguini_ir::validate_ir(&schema, &regional).expect("regional locale is independently valid");

    let error = ValidatedTypeScriptProject::try_new(
        &schema,
        &[
            TypeScriptLocaleModule {
                locale: "en".to_owned(),
                module: base,
            },
            TypeScriptLocaleModule {
                locale: "en-US".to_owned(),
                module: regional,
            },
        ],
        &TypeScriptProjectOptions {
            base_locale: Some("en".to_owned()),
            ..TypeScriptProjectOptions::default()
        },
    )
    .expect_err("invalid fallback composition must be rejected");

    let TypeScriptCodegenError::InvalidIr { scope, errors } = error else {
        panic!("expected invalid IR error");
    };
    assert_eq!(scope, "locale `en-US`");
    assert!(errors.iter().any(|error| error.code == "IR027"));
}

#[test]
fn project_fallback_chain_uses_cldr_parent_locales() {
    use crate::module::locale_fallback_chain;
    use linguini_ir::IrModule;

    let locales = ["en", "en-001", "en-AU"]
        .map(|locale| TypeScriptLocaleModule {
            locale: locale.to_owned(),
            module: IrModule::default(),
        })
        .to_vec();

    assert_eq!(
        locale_fallback_chain(&locales, "en-AU", Some("en")),
        ["en-AU", "en-001", "en"]
    );
}

#[test]
fn project_fallback_chain_uses_likely_scripts_and_aliases() {
    use crate::module::locale_fallback_chain;
    use linguini_ir::IrModule;

    let locales = ["en", "zh-Hant", "zh-TW", "he-IL", "iw-IL", "he"]
        .map(|locale| TypeScriptLocaleModule {
            locale: locale.to_owned(),
            module: IrModule::default(),
        })
        .to_vec();

    assert_eq!(
        locale_fallback_chain(&locales, "zh-TW", Some("en")),
        ["zh-TW", "zh-Hant", "en"]
    );
    assert_eq!(
        locale_fallback_chain(&locales, "iw-IL", Some("en")),
        ["iw-IL", "he", "en"]
    );
}

#[test]
fn project_runtime_embeds_cldr_resolution_overrides() {
    use linguini_ir::IrModule;

    let locales = ["en", "en-001", "zh-Hant"]
        .map(|locale| TypeScriptLocaleModule {
            locale: locale.to_owned(),
            module: IrModule::default(),
        })
        .to_vec();
    let files = generate_project_files(
        &IrModule::default(),
        &locales,
        &TypeScriptProjectOptions {
            base_locale: Some("en".to_owned()),
            ..TypeScriptProjectOptions::default()
        },
    )
    .expect("project codegen");
    let locale = files
        .iter()
        .find(|file| file.path == "locale.ts")
        .expect("runtime locale");

    assert!(locale.contents.contains(r#""en-au": "en-001""#));
    assert!(locale.contents.contains(r#""zh-tw": "zh-Hant""#));
    assert!(locale.contents.contains("isLanguageScriptTag(tag)"));
}

#[test]
fn project_codegen_emits_schema_namespace_objects() {
    use linguini_ir::{IrMessage, IrModule, IrText, IrTextBlockMode, IrTextPart};
    use linguini_syntax::Span;

    fn schema_message(name: &str) -> IrMessage {
        IrMessage {
            name: name.to_owned(),
            docs: Vec::new(),
            parameters: Vec::new(),
            body: None,
        }
    }

    fn locale_message(name: &str, value: &str) -> IrMessage {
        IrMessage {
            name: name.to_owned(),
            docs: Vec::new(),
            parameters: Vec::new(),
            body: Some(IrText {
                parts: vec![IrTextPart::Text(value.to_owned())],
                mode: IrTextBlockMode::Inline,
                span: Span::new(0, value.len()),
            }),
        }
    }

    let schema = IrModule {
        messages: vec![
            schema_message("checkout.order_ready"),
            schema_message("checkout.cart_summary"),
        ],
        ..IrModule::default()
    };
    let locale = IrModule {
        messages: vec![
            locale_message("checkout.order_ready", "Ready"),
            locale_message("checkout.cart_summary", "Cart"),
        ],
        ..IrModule::default()
    };

    let files = generate_project_files(
        &schema,
        &[TypeScriptLocaleModule {
            locale: "en".to_owned(),
            module: locale,
        }],
        &project_options("en"),
    )
    .expect("project codegen");

    let locale_module = files
        .iter()
        .find(|file| file.path == "locales/en.ts")
        .expect("locale module");
    assert!(locale_module
        .contents
        .contains("import { checkout } from \"./en/checkout\";"));
    assert!(locale_module.contents.contains("  checkout,"));

    let checkout_module = files
        .iter()
        .find(|file| file.path == "locales/en/checkout.ts")
        .expect("checkout locale module");
    assert!(checkout_module.contents.contains("order_ready: \"Ready\""));
    assert!(checkout_module.contents.contains("cart_summary: \"Cart\""));

    let declaration = files
        .iter()
        .find(|file| file.path == "locales/en.d.ts")
        .expect("locale declaration");
    assert!(declaration
        .contents
        .contains("export declare const checkout: typeof checkout;"));
}

#[test]
fn project_codegen_emits_generated_sveltekit_adapter_when_enabled() {
    use crate::{
        TypeScriptFramework, TypeScriptLocaleModule, TypeScriptLocaleSource,
        TypeScriptProjectOptions, TypeScriptWebOptions,
    };
    use linguini_ir::IrModule;

    let files = generate_project_files(
        &IrModule::default(),
        &[TypeScriptLocaleModule {
            locale: "en".to_owned(),
            module: IrModule::default(),
        }],
        &TypeScriptProjectOptions {
            framework: Some(TypeScriptFramework::SvelteKit),
            web: Some(TypeScriptWebOptions {
                sources: vec![
                    TypeScriptLocaleSource::Path,
                    TypeScriptLocaleSource::Cookie,
                    TypeScriptLocaleSource::AcceptLanguage,
                ],
                cookie_name: "SHOP_LOCALE".to_owned(),
                cookie_path: "/shop".to_owned(),
                cookie_domain: Some("example.com".to_owned()),
                cookie_max_age: 86400,
                cookie_same_site: "strict".to_owned(),
                cookie_secure: true,
                cookie_http_only: true,
                local_storage_key: "SHOP_LOCALE".to_owned(),
                prefix_default_locale: true,
                base_path: "/shop".to_owned(),
                redirect: false,
                origin: Some("https://example.com".to_owned()),
                exclude: vec!["/api/**".to_owned()],
                localize_links: false,
            }),
            ..project_options("en")
        },
    )
    .expect("project codegen");

    let paths = files
        .iter()
        .map(|file| file.path.as_str())
        .collect::<Vec<_>>();
    assert!(paths.contains(&"svelte.ts"));
    assert!(paths.contains(&"svelte-control.ts"));
    assert!(paths.contains(&"svelte-control.d.ts"));
    assert!(paths.contains(&"svelte-locale.svelte.ts"));
    assert!(paths.contains(&"svelte-locale.svelte.d.ts"));
    assert!(paths.contains(&"svelte-effects.svelte.ts"));
    assert!(paths.contains(&"svelte-effects.svelte.d.ts"));
    assert!(paths.contains(&"web.ts"));
    assert!(paths.contains(&"sveltekit-control.ts"));
    assert!(paths.contains(&"sveltekit-control.d.ts"));
    assert!(paths.contains(&"sveltekit.ts"));

    let svelte = files
        .iter()
        .find(|file| file.path == "svelte.ts")
        .expect("svelte module");
    let svelte_control = files
        .iter()
        .find(|file| file.path == "svelte-control.ts")
        .expect("Svelte control module");
    assert!(svelte_control
        .contents
        .contains("./svelte-effects.svelte.js"));
    assert!(svelte_control
        .contents
        .contains("from \"$app/environment\""));
    assert!(svelte_control.contents.contains("from \"$app/navigation\""));
    assert!(!svelte.contents.contains("createWebI18n"));
    assert!(!svelte.contents.contains("@antepod/"));
    assert!(svelte.contents.contains("export const l = linguini.l;"));
    assert!(svelte.contents.contains("./svelte-control.js"));
    assert!(svelte.contents.contains("getLocale: () => controls.locale"));
    assert!(svelte.contents.contains("get locale()"));
    assert!(!svelte.contents.contains("...controls"));
    let svelte_declaration = files
        .iter()
        .find(|file| file.path == "svelte.d.ts")
        .expect("Svelte declaration");
    assert!(svelte_declaration
        .contents
        .contains("export type { LinguiniSetLocaleOptions }"));
    assert!(svelte_control.contents.contains("cookie: true"));
    assert!(svelte_control.contents.contains("navigate: true"));
    assert!(svelte_control.contents.contains("keepFocus: true"));
    assert!(svelte_control.contents.contains("noScroll: true"));
    assert!(svelte_control
        .contents
        .contains("setCurrentLocale(resolved)"));
    assert!(svelte_control
        .contents
        .contains("writeLocaleCookie(web, resolved)"));
    assert!(svelte_control
        .contents
        .contains("clearCurrentLocaleOverride()"));
    assert!(svelte_control
        .contents
        .contains("./svelte-locale.svelte.js"));
    assert!(svelte_control.contents.contains("refreshLinguiniEffects()"));
    assert!(svelte_control
        .contents
        .contains("destroy: destroyLinguiniEffects"));
    for forbidden in ["./index", "./locales/", "./messages"] {
        assert!(!svelte_control.contents.contains(forbidden));
    }
    for forbidden in [
        "MutationObserver",
        "AUTO_LINK_MAX_PENDING_ROOTS",
        "initializeCurrentLocale",
        "hot?.dispose",
    ] {
        assert!(!svelte_control.contents.contains(forbidden));
    }

    let svelte_effects = files
        .iter()
        .find(|file| file.path == "svelte-effects.svelte.ts")
        .expect("Svelte effects helper");
    assert!(svelte_effects.contents.contains("createWebLocaleI18n"));
    assert!(svelte_effects
        .contents
        .contains("from \"$app/environment\""));
    assert!(svelte_effects
        .contents
        .contains("initializeCurrentLocale(readInitialLocale())"));
    assert!(svelte_effects
        .contents
        .contains("startAutoLinkLocalization(getCurrentLocale)"));
    assert!(svelte_effects
        .contents
        .contains("hot?.dispose(destroyLinguiniEffects)"));
    assert!(svelte_effects
        .contents
        .contains("cookieName: \"SHOP_LOCALE\""));
    assert!(svelte_effects
        .contents
        .contains("sources: [\"path\", \"cookie\", \"accept-language\"] as const"));
    assert!(svelte_effects.contents.contains("localizeLinks: false"));
    for capability in [
        "readBrowserCapability(() => window.location.href)",
        "readBrowserCapability(() => document.cookie)",
        "readBrowserCapability(() => window.localStorage)",
        "readBrowserCapability(() => window.navigator)",
    ] {
        assert!(svelte_effects.contents.contains(capability));
    }
    for forbidden in ["./index", "./locales/", "./messages", "createLinguini"] {
        assert!(!svelte_effects.contents.contains(forbidden));
    }
    let svelte_effects_declaration = files
        .iter()
        .find(|file| file.path == "svelte-effects.svelte.d.ts")
        .expect("Svelte effects helper declaration");
    for export in ["web", "refreshLinguiniEffects", "destroyLinguiniEffects"] {
        assert!(svelte_effects_declaration.contents.contains(export));
    }

    let svelte_locale = files
        .iter()
        .find(|file| file.path == "svelte-locale.svelte.ts")
        .expect("Svelte locale helper");
    assert!(svelte_locale.contents.contains("from \"$app/state\""));
    assert!(svelte_locale
        .contents
        .contains("let clientLocale = $state<Locale>(baseLocale)"));
    assert!(svelte_locale
        .contents
        .contains("let hasClientOverride = $state(false)"));
    assert!(svelte_locale.contents.contains("hasClientOverride\n    ? resolvedClientLocale\n    : normalizeLocale(dataLocale) ?? resolvedClientLocale"));
    assert!(svelte_locale.contents.contains("hasClientOverride = true"));
    assert!(svelte_locale.contents.contains("hasClientOverride = false"));
    assert!(svelte_locale.contents.contains("from \"./locale\""));
    assert!(!svelte_locale.contents.contains("export let clientLocale"));
    assert!(!svelte_locale
        .contents
        .contains("export let hasClientOverride"));
    for forbidden in ["./index", "./locales/", "./messages", "createWebI18n"] {
        assert!(!svelte_locale.contents.contains(forbidden));
    }
    let svelte_locale_declaration = files
        .iter()
        .find(|file| file.path == "svelte-locale.svelte.d.ts")
        .expect("Svelte locale helper declaration");
    assert!(svelte_locale_declaration
        .contents
        .contains("initializeCurrentLocale"));
    assert!(svelte_locale_declaration
        .contents
        .contains("clearCurrentLocaleOverride"));

    let goto_position = svelte_control
        .contents
        .find("await goto(")
        .expect("goto call");
    let clear_position = svelte_control
        .contents
        .find("clearCurrentLocaleOverride();")
        .expect("override clear");
    assert!(clear_position > goto_position);

    let sveltekit = files
        .iter()
        .find(|file| file.path == "sveltekit.ts")
        .expect("sveltekit module");
    assert!(sveltekit
        .contents
        .contains("import { createWebI18n } from \"./web\";"));
    assert!(sveltekit
        .contents
        .contains("import * as runtime from \"./index\";"));
    assert!(!sveltekit.contents.contains("@antepod/"));
    assert!(sveltekit.contents.contains("export const handle"));
    assert!(sveltekit.contents.contains("export const reroute"));
    assert!(sveltekit.contents.contains("export const load"));
    assert!(sveltekit
        .contents
        .contains("cookie: event.request.headers.get(\"cookie\") ?? undefined"));

    let sveltekit_control = files
        .iter()
        .find(|file| file.path == "sveltekit-control.ts")
        .expect("sveltekit control module");
    assert!(sveltekit_control
        .contents
        .contains("import type { Locale } from \"./locale\";"));
    assert!(sveltekit_control
        .contents
        .contains("LinguiniWebLocale<Locale>"));
    assert!(sveltekit_control.contents.contains("resolved: Locale"));
    assert!(sveltekit_control
        .contents
        .contains("import { createWebLocaleI18n } from \"./web\";"));
    assert!(sveltekit_control
        .contents
        .contains("import * as locale from \"./locale\";"));
    for forbidden in ["./index", "./locales/", "./messages", "createWebI18n"] {
        assert!(!sveltekit_control.contents.contains(forbidden));
    }

    let sveltekit_control_declaration = files
        .iter()
        .find(|file| file.path == "sveltekit-control.d.ts")
        .expect("sveltekit control declaration");
    assert!(sveltekit_control_declaration
        .contents
        .contains("interface LinguiniServerLocaleContext"));
    assert!(sveltekit_control_declaration.contents.contains(
        "export type LinguiniSvelteKitLocaleContext = LinguiniServerLocaleContext<Locale>"
    ));
    for forbidden in ["LinguiniRequestContext", "./index", "declare global"] {
        assert!(!sveltekit_control_declaration.contents.contains(forbidden));
    }

    let sveltekit_declaration = files
        .iter()
        .find(|file| file.path == "sveltekit.d.ts")
        .expect("sveltekit declaration");
    assert!(sveltekit_declaration
        .contents
        .contains("interface SerializedLinguiniContext"));
    assert!(sveltekit_declaration.contents.contains("interface Locals"));
    assert!(sveltekit_declaration
        .contents
        .contains("linguini: LinguiniRequestContext<Locale, Linguini>"));
    assert!(sveltekit_declaration.contents.contains("Linguini>"));
    assert!(sveltekit_declaration.contents.contains("./index"));
    assert!(!sveltekit_declaration.contents.contains("@antepod/"));
}

#[test]
fn project_codegen_emits_plain_svelte_web_runtime_without_sveltekit_imports() {
    use crate::{
        TypeScriptFramework, TypeScriptLocaleModule, TypeScriptProjectOptions, TypeScriptWebOptions,
    };
    use linguini_ir::IrModule;

    let files = generate_project_files(
        &IrModule::default(),
        &[TypeScriptLocaleModule {
            locale: "en".to_owned(),
            module: IrModule::default(),
        }],
        &TypeScriptProjectOptions {
            framework: Some(TypeScriptFramework::Svelte),
            web: Some(TypeScriptWebOptions::default()),
            ..project_options("en")
        },
    )
    .expect("plain Svelte web codegen");

    let paths = files
        .iter()
        .map(|file| file.path.as_str())
        .collect::<Vec<_>>();
    for path in [
        "web.ts",
        "svelte.ts",
        "svelte.d.ts",
        "svelte-control.ts",
        "svelte-control.d.ts",
        "svelte-locale.svelte.ts",
        "svelte-effects.svelte.ts",
    ] {
        assert!(paths.contains(&path));
    }
    assert!(!paths.contains(&"sveltekit.ts"));

    let generated = |path: &str| {
        &files
            .iter()
            .find(|file| file.path == path)
            .unwrap_or_else(|| panic!("missing {path}"))
            .contents
    };
    let svelte = generated("svelte.ts");
    let control = generated("svelte-control.ts");
    let locale = generated("svelte-locale.svelte.ts");
    let effects = generated("svelte-effects.svelte.ts");
    let declaration = generated("svelte-control.d.ts");

    for output in [svelte, control, locale, effects, declaration] {
        assert!(!output.contains("$app/"));
    }
    assert!(control.contains("typeof window !== \"undefined\""));
    assert!(control.contains("window.location.assign(href)"));
    assert!(control.contains("window.location.replace(href)"));
    assert!(!control.contains("goto("));
    assert!(!control.contains("clearCurrentLocaleOverride"));
    assert!(effects.contains("typeof document !== \"undefined\""));
    assert!(effects.contains("initializeCurrentLocale(readInitialLocale())"));
    assert!(effects.contains("readBrowserCapability(() => document.cookie)"));
    assert!(effects.contains("readBrowserCapability(() => window.localStorage)"));
    assert!(effects.contains("readBrowserCapability(() => window.navigator)"));
    assert!(locale.contains("let activeLocale = $state<Locale>(baseLocale)"));
    assert!(locale.contains("export function initializeCurrentLocale"));
    assert!(locale.contains("export function setCurrentLocale"));
    assert!(declaration.contains("state?: unknown"));
    let set_position = control
        .find("setCurrentLocale(resolved)")
        .expect("synchronous locale update");
    let navigation_position = control
        .find("if (options.navigate)")
        .expect("navigation branch");
    assert!(set_position < navigation_position);
    assert!(control.contains("writeLocaleCookie(web, resolved)"));
    assert!(svelte.contains("get locale()"));
    assert!(!svelte.contains("...controls"));
    for forbidden in ["./index", "./locales/", "./messages"] {
        assert!(!control.contains(forbidden));
    }
    for forbidden in ["./index", "./locales/", "./messages", "createLinguini"] {
        assert!(!effects.contains(forbidden));
    }
}

#[test]
fn project_codegen_emits_context_only_svelte_without_web_config() {
    use crate::{TypeScriptFramework, TypeScriptLocaleModule, TypeScriptProjectOptions};
    use linguini_ir::IrModule;

    let files = generate_project_files(
        &IrModule::default(),
        &[TypeScriptLocaleModule {
            locale: "en".to_owned(),
            module: IrModule::default(),
        }],
        &TypeScriptProjectOptions {
            framework: Some(TypeScriptFramework::SvelteKit),
            web: None,
            ..project_options("en")
        },
    )
    .expect("project codegen");

    let paths = files
        .iter()
        .map(|file| file.path.as_str())
        .collect::<Vec<_>>();
    assert!(paths.contains(&"svelte.ts"));
    assert!(paths.contains(&"svelte-locale.svelte.ts"));
    assert!(!paths.contains(&"svelte-control.ts"));
    assert!(!paths.contains(&"svelte-control.d.ts"));
    assert!(!paths.contains(&"svelte-effects.svelte.ts"));
    assert!(!paths.contains(&"svelte-effects.svelte.d.ts"));
    assert!(!paths.contains(&"web.ts"));
    assert!(!paths.contains(&"sveltekit.ts"));

    let svelte = files
        .iter()
        .find(|file| file.path == "svelte.ts")
        .expect("svelte module");
    assert!(svelte.contents.contains("getLocale: getCurrentLocale"));
    assert!(!svelte.contents.contains("$app/navigation"));
    assert!(!svelte.contents.contains("createWebI18n"));

    let svelte_locale = files
        .iter()
        .find(|file| file.path == "svelte-locale.svelte.ts")
        .expect("context locale helper");
    assert!(svelte_locale
        .contents
        .contains("let activeLocale = $state<Locale>(baseLocale)"));
    assert!(svelte_locale
        .contents
        .contains("normalizeLocale(locale) ?? baseLocale"));
    assert!(!svelte_locale.contents.contains("$app/"));
    assert!(!svelte_locale.contents.contains("./index"));
    assert!(!svelte_locale.contents.contains("./locales/"));
    assert!(!svelte_locale.contents.contains("export let activeLocale"));
    assert!(svelte.contents.contains("./svelte-locale.svelte.js"));
    let svelte_locale_declaration = files
        .iter()
        .find(|file| file.path == "svelte-locale.svelte.d.ts")
        .expect("context locale helper declaration");
    assert!(svelte_locale_declaration
        .contents
        .contains("setCurrentLocale"));
    assert!(!svelte_locale_declaration
        .contents
        .contains("initializeCurrentLocale"));
    assert!(!svelte_locale_declaration
        .contents
        .contains("clearCurrentLocaleOverride"));
}

#[test]
fn project_codegen_uses_cldr_text_direction_metadata() {
    use crate::{TypeScriptLocaleModule, TypeScriptProjectOptions};
    use linguini_ir::IrModule;

    let files = generate_project_files(
        &IrModule::default(),
        &[
            TypeScriptLocaleModule {
                locale: "en".to_owned(),
                module: IrModule::default(),
            },
            TypeScriptLocaleModule {
                locale: "ar".to_owned(),
                module: IrModule::default(),
            },
        ],
        &TypeScriptProjectOptions {
            base_locale: Some("en".to_owned()),
            ..TypeScriptProjectOptions::default()
        },
    )
    .expect("project codegen");

    let locale = files
        .iter()
        .find(|file| file.path == "locale.ts")
        .expect("locale module");
    assert!(locale.contents.contains(r#"en: "ltr""#));
    assert!(locale.contents.contains(r#"ar: "rtl""#));
}
