use crate::{
    TypeScriptCodegenError, TypeScriptGeneratedFile, TypeScriptLocaleModule,
    TypeScriptProjectOptions, ValidatedTypeScriptProject,
};
use linguini_ir::{lower_locale, lower_schema};
use linguini_syntax::{parse_locale, parse_schema};
use std::fs;
use std::path::Path;

fn generate_project_files(
    schema: &linguini_ir::IrModule,
    locales: &[TypeScriptLocaleModule],
    options: &TypeScriptProjectOptions,
) -> Result<Vec<TypeScriptGeneratedFile>, TypeScriptCodegenError> {
    let project = ValidatedTypeScriptProject::try_new(schema, locales, options)?;
    crate::generate_typescript_project_files(&project)
}

fn project_options(base_locale: &str) -> TypeScriptProjectOptions {
    TypeScriptProjectOptions {
        base_locale: Some(base_locale.to_owned()),
        ..TypeScriptProjectOptions::default()
    }
}

#[test]
fn generated_module_snapshot_is_stable() {
    let schema = parse_schema(include_str!(
        "../../../tests/fixtures/golden/schema/shop.lgs"
    ))
    .expect("schema");
    let locale =
        parse_locale(include_str!("../../../tests/fixtures/golden/locale/ru.lgl")).expect("locale");

    let files = generate_project_files(
        &lower_schema(&schema),
        &[TypeScriptLocaleModule {
            locale: "ru".to_owned(),
            module: lower_locale(&locale),
        }],
        &TypeScriptProjectOptions {
            declaration: true,
            tree_shaking: false,
            included_messages: Vec::new(),
            base_locale: Some("ru".to_owned()),
            ..TypeScriptProjectOptions::default()
        },
    )
    .expect("project files");

    for file in files {
        if file.path == ".gitignore" {
            assert_eq!(file.contents, "# Generated by Linguini. Do not edit.\n*\n");
            continue;
        }
        let snapshot_path = format!("tests/fixtures/golden/snapshots/ts/{}", file.path);
        assert_snapshot(&snapshot_path, &file.contents);
    }
}

fn assert_snapshot(path: &str, snapshot: &str) {
    if std::env::var_os("LINGUINI_UPDATE_SNAPSHOTS").is_some() {
        let path = repo_root().join(path);
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent).expect("create snapshot dir");
        }
        fs::write(path, snapshot).expect("write snapshot");
    }

    let expected = fs::read_to_string(repo_root().join(path)).expect("read snapshot");
    assert_eq!(snapshot, expected);
}

fn repo_root() -> &'static Path {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(Path::parent)
        .expect("repo root")
}

#[test]
fn project_codegen_owns_multilocale_index_files() {
    use crate::{TypeScriptLocaleModule, TypeScriptProjectOptions};
    use linguini_ir::IrModule;

    let files = generate_project_files(
        &IrModule::default(),
        &[
            TypeScriptLocaleModule {
                locale: "en".to_owned(),
                module: IrModule::default(),
            },
            TypeScriptLocaleModule {
                locale: "ru".to_owned(),
                module: IrModule::default(),
            },
        ],
        &TypeScriptProjectOptions {
            declaration: true,
            tree_shaking: false,
            included_messages: Vec::new(),
            base_locale: Some("en".to_owned()),
            ..TypeScriptProjectOptions::default()
        },
    )
    .expect("project codegen");

    let index = files
        .iter()
        .find(|file| file.path == "index.ts")
        .expect("index.ts");
    assert!(index
        .contents
        .contains("import locale_en from \"./locales/en\";"));
    assert!(index
        .contents
        .contains("import locale_ru from \"./locales/ru\";"));
    assert!(index.contents.contains("ru: locale_ru"));
    let gitignore = files
        .iter()
        .find(|file| file.path == ".gitignore")
        .expect("generated gitignore");
    assert_eq!(
        gitignore.contents,
        "# Generated by Linguini. Do not edit.\n*\n"
    );
    assert_eq!(
        files
            .iter()
            .map(|file| file.path.as_str())
            .collect::<Vec<_>>(),
        [
            "shared.ts",
            ".gitignore",
            "shared.d.ts",
            "locales/en.ts",
            "locales/en.d.ts",
            "locales/ru.ts",
            "locales/ru.d.ts",
            "index.ts",
            "index.d.ts",
        ]
    );
    for forbidden in [
        ["coo", "kie"].concat(),
        ["localize", "Href"].concat(),
        ["Middle", "ware"].concat(),
    ] {
        assert!(!index.contents.contains(&forbidden));
    }
}

#[test]
fn project_codegen_can_omit_generated_gitignore() {
    use linguini_ir::IrModule;

    let files = generate_project_files(
        &IrModule::default(),
        &[TypeScriptLocaleModule {
            locale: "en".to_owned(),
            module: IrModule::default(),
        }],
        &TypeScriptProjectOptions {
            gitignore: false,
            ..project_options("en")
        },
    )
    .expect("project codegen");

    assert!(!files.iter().any(|file| file.path == ".gitignore"));
}

#[test]
fn project_runtime_index_snapshot_is_stable() {
    use linguini_ir::IrModule;

    let files = generate_project_files(
        &IrModule::default(),
        &[
            TypeScriptLocaleModule {
                locale: "en".to_owned(),
                module: IrModule::default(),
            },
            TypeScriptLocaleModule {
                locale: "ru".to_owned(),
                module: IrModule::default(),
            },
        ],
        &TypeScriptProjectOptions {
            declaration: true,
            tree_shaking: false,
            included_messages: Vec::new(),
            base_locale: Some("en".to_owned()),
            ..TypeScriptProjectOptions::default()
        },
    )
    .expect("project codegen");

    let index = files
        .iter()
        .find(|file| file.path == "index.ts")
        .expect("index.ts");
    assert_snapshot(
        "tests/fixtures/golden/snapshots/ts-runtime/index.ts",
        &index.contents,
    );
}

#[test]
fn project_codegen_filters_messages_in_tree_shaking_mode() {
    use crate::{TypeScriptLocaleModule, TypeScriptProjectOptions};

    let schema = lower_schema(&parse_schema("keep\ndrop\ngroup { label help }\n").expect("schema"));
    let locale = lower_locale(
        &parse_locale("keep = Keep\ndrop = Drop\ngroup {\n  label = Label\n  help = Help\n}\n")
            .expect("locale"),
    );

    let files = generate_project_files(
        &schema,
        &[TypeScriptLocaleModule {
            locale: "en".to_owned(),
            module: locale,
        }],
        &TypeScriptProjectOptions {
            declaration: true,
            tree_shaking: true,
            included_messages: vec!["keep".to_owned(), "group.label".to_owned()],
            base_locale: Some("en".to_owned()),
            ..TypeScriptProjectOptions::default()
        },
    )
    .expect("project codegen");

    let locale_module = files
        .iter()
        .find(|file| file.path == "locales/en.ts")
        .expect("locale module");
    assert!(locale_module.contents.contains("export function keep"));
    assert!(!locale_module.contents.contains("export function drop"));
    assert!(locale_module
        .contents
        .contains("import { group } from \"./en/group\";"));

    let group_module = files
        .iter()
        .find(|file| file.path == "locales/en/group.ts")
        .expect("group locale module");
    assert!(group_module.contents.contains("label: \"Label\""));
    assert!(!group_module.contents.contains("help: \"Help\""));
    assert!(!locale_module.contents.contains("help: \"Help\""));
}

#[test]
fn project_codegen_applies_schema_formatter_aliases() {
    let schema = lower_schema(
        &parse_schema(
            r#"
type Price = Number @currency(code = "EUR")
type ShortDate = Date @date(style = "short")
total(price: Price, created: ShortDate)
plain(price: Price)
"#,
        )
        .expect("schema"),
    );
    let locale = lower_locale(
        &parse_locale(
            r#"
total = Total {price} on {created}
plain = Raw {price @number}
"#,
        )
        .expect("locale"),
    );

    let files = generate_project_files(
        &schema,
        &[TypeScriptLocaleModule {
            locale: "en".to_owned(),
            module: locale,
        }],
        &project_options("en"),
    )
    .expect("project codegen");

    let locale_module = files
        .iter()
        .find(|file| file.path == "locales/en.ts")
        .expect("locale module");
    assert!(!locale_module.contents.contains("FORMATTER_DATA"));
    assert!(!locale_module.contents.contains("GeneratedNumberPattern"));
    assert!(!locale_module.contents.contains("Intl.DateTimeFormat"));
    assert!(!locale_module.contents.contains("replace(/[#0"));
    assert!(locale_module.contents.contains("function formatCurrency("));
    assert!(locale_module
        .contents
        .contains("formatCurrency(price, { code: \"EUR\" })"));
    assert!(locale_module.contents.contains("function formatDate("));
    assert!(locale_module
        .contents
        .contains("const date = coerceDate(value);"));
    assert!(locale_module
        .contents
        .contains("function coerceDate(value: Date | number | string): Date"));
    assert!(locale_module
        .contents
        .contains("formatDate(created, { style: \"short\" })"));
    let shared_module = files
        .iter()
        .find(|file| file.path == "shared.ts")
        .expect("shared module");
    assert!(shared_module
        .contents
        .contains("export type ShortDate = Date | number | string;"));
    assert!(locale_module
        .contents
        .contains("export function plain(price: Price): string"));
    assert!(locale_module.contents.contains("formatNumber(price)"));
}

#[test]
fn project_codegen_applies_primitive_schema_formatters() {
    let schema = lower_schema(
        &parse_schema("summary(count: Number, amount: Decimal, created: Date)\n").expect("schema"),
    );
    let locale =
        lower_locale(&parse_locale("summary = {count} / {amount} / {created}\n").expect("locale"));

    let files = generate_project_files(
        &schema,
        &[TypeScriptLocaleModule {
            locale: "en".to_owned(),
            module: locale,
        }],
        &project_options("en"),
    )
    .expect("project codegen");

    let locale_module = files
        .iter()
        .find(|file| file.path == "locales/en.ts")
        .expect("locale module");
    assert!(locale_module.contents.contains("formatNumber(count)"));
    assert!(locale_module.contents.contains("formatNumber(amount)"));
    assert!(locale_module.contents.contains("formatDate(created"));
}

#[test]
fn project_codegen_emits_callable_form_variants_with_attributes() {
    let schema = lower_schema(
        &parse_schema("enum Fruit { apple }\nlabel(fruit: Fruit, count: Number)\n")
            .expect("schema"),
    );
    let locale = lower_locale(
        &parse_locale(
            r#"
impl Fruit {
  apple {
    one => apple
    _ => apples
    label = Apple
  }
}
label = {fruit(count)}: {fruit.label}
"#,
        )
        .expect("locale"),
    );

    let locale_module =
        crate::module::generate_unvalidated_typescript_module_for_test(&schema, &locale, "en");
    assert!(locale_module.contains(
        "apple: Object.assign((value: number | string) => \
selectBranch(pluralEn(value), { one: \"apple\", _: \"apples\" }), { label: \"Apple\" })"
    ));
    assert!(locale_module.contains(
        "return String(__lgl_form_4672756974[fruit](count)) + \": \" + \
String(__lgl_form_4672756974[fruit].label);"
    ));
}

#[test]
fn project_codegen_preserves_every_multi_key_branch() {
    let schema = lower_schema(
        &parse_schema("enum Fruit { apple }\nlabel(fruit: Fruit, count: Number)\n")
            .expect("schema"),
    );
    let locale = lower_locale(
        &parse_locale(
            r#"
impl Fruit {
  apple {
    one, few, many => apples
    _ => fruit
  }
}
label = {fruit(count)}
"#,
        )
        .expect("locale"),
    );

    let locale_module =
        crate::module::generate_unvalidated_typescript_module_for_test(&schema, &locale, "en");
    assert!(locale_module.contains(
        "apple: (value: number | string) => selectBranch(pluralEn(value), \
{ one: \"apples\", few: \"apples\", many: \"apples\", _: \"fruit\" })"
    ));
}

#[test]
fn project_validation_rejects_an_empty_locale_set() {
    let error = ValidatedTypeScriptProject::try_new(
        &linguini_ir::IrModule::default(),
        &[],
        &project_options("en"),
    )
    .expect_err("an empty locale set must be rejected");

    assert_eq!(error, TypeScriptCodegenError::EmptyLocaleSet);
}

#[test]
fn project_validation_rejects_duplicate_and_case_folded_locales() {
    use linguini_ir::IrModule;

    for conflicting_locale in ["en", "EN"] {
        let error = ValidatedTypeScriptProject::try_new(
            &IrModule::default(),
            &[
                TypeScriptLocaleModule {
                    locale: "en".to_owned(),
                    module: IrModule::default(),
                },
                TypeScriptLocaleModule {
                    locale: conflicting_locale.to_owned(),
                    module: IrModule::default(),
                },
            ],
            &project_options("en"),
        )
        .expect_err("case-folded locale collisions must be rejected");

        assert_eq!(
            error,
            TypeScriptCodegenError::DuplicateLocale {
                locale: conflicting_locale.to_owned(),
                conflicts_with: "en".to_owned(),
            }
        );
    }
}

#[test]
fn project_validation_requires_an_explicit_base_locale() {
    use linguini_ir::IrModule;

    let error = ValidatedTypeScriptProject::try_new(
        &IrModule::default(),
        &[TypeScriptLocaleModule {
            locale: "en".to_owned(),
            module: IrModule::default(),
        }],
        &TypeScriptProjectOptions::default(),
    )
    .expect_err("a missing base locale must not fall back to the first locale");

    assert_eq!(error, TypeScriptCodegenError::MissingBaseLocale);
}

#[test]
fn project_validation_rejects_an_unknown_base_locale() {
    use linguini_ir::IrModule;

    let error = ValidatedTypeScriptProject::try_new(
        &IrModule::default(),
        &[TypeScriptLocaleModule {
            locale: "en".to_owned(),
            module: IrModule::default(),
        }],
        &project_options("fr"),
    )
    .expect_err("an unknown base locale must not fall back to the first locale");

    assert_eq!(
        error,
        TypeScriptCodegenError::UnknownBaseLocale {
            base_locale: "fr".to_owned(),
        }
    );
}

#[test]
fn project_validation_rejects_unknown_included_messages() {
    use linguini_ir::IrModule;

    let schema = lower_schema(&parse_schema("known\naccount { title }\n").expect("schema"));
    let options = TypeScriptProjectOptions {
        tree_shaking: true,
        included_messages: vec!["missing".to_owned()],
        ..project_options("en")
    };
    let error = ValidatedTypeScriptProject::try_new(
        &schema,
        &[TypeScriptLocaleModule {
            locale: "en".to_owned(),
            module: IrModule::default(),
        }],
        &options,
    )
    .expect_err("unknown tree-shaking roots must be rejected");

    assert_eq!(
        error,
        TypeScriptCodegenError::UnknownIncludedMessage {
            message: "missing".to_owned(),
        }
    );
}

#[test]
fn project_validation_rejects_locales_without_cldr_text_direction() {
    use linguini_ir::IrModule;

    let error = ValidatedTypeScriptProject::try_new(
        &IrModule::default(),
        &[TypeScriptLocaleModule {
            locale: "zz-ZZ".to_owned(),
            module: IrModule::default(),
        }],
        &project_options("zz-ZZ"),
    )
    .expect_err("an unknown text direction must not be coerced to LTR");

    assert_eq!(
        error,
        TypeScriptCodegenError::MissingTextDirection {
            locale: "zz-ZZ".to_owned(),
        }
    );
}

#[test]
fn project_validation_rejects_formatter_alias_cycles() {
    let schema = lower_schema(
        &parse_schema("type First = Second\ntype Second = First\nlabel(value: First)\n")
            .expect("schema"),
    );
    let locale = lower_locale(&parse_locale("label = {value}\n").expect("locale implementation"));

    let error = ValidatedTypeScriptProject::try_new(
        &schema,
        &[TypeScriptLocaleModule {
            locale: "en".to_owned(),
            module: locale,
        }],
        &project_options("en"),
    )
    .expect_err("cyclic aliases must be rejected before codegen");

    let TypeScriptCodegenError::InvalidIr { errors, .. } = error else {
        panic!("expected invalid IR error");
    };
    assert!(errors.iter().any(|error| error.code == "IR008"));
}

#[test]
fn project_validation_rejects_unresolved_locale_messages() {
    let schema = lower_schema(&parse_schema("known\n").expect("schema"));
    let locale = lower_locale(&parse_locale("unknown = Unknown\n").expect("locale"));

    let error = ValidatedTypeScriptProject::try_new(
        &schema,
        &[TypeScriptLocaleModule {
            locale: "en".to_owned(),
            module: locale,
        }],
        &project_options("en"),
    )
    .expect_err("unresolved locale message must be rejected");

    let TypeScriptCodegenError::InvalidIr { scope, errors } = error else {
        panic!("expected invalid IR error");
    };
    assert_eq!(scope, "locale `en`");
    assert!(errors.iter().any(|error| error.code == "IR010"));
}

#[test]
fn project_validation_checks_fallback_composed_modules() {
    let schema = lower_schema(&parse_schema("greeting\n").expect("schema"));
    let base = lower_locale(
        &parse_locale(
            r#"
let name = Base
fn Wrap(value: String) {
  _ => {value}
}
greeting = {Wrap(name)}
"#,
        )
        .expect("base locale"),
    );
    let regional = lower_locale(
        &parse_locale(
            r#"
fn Wrap(value: Number) {
  _ => {value}
}
"#,
        )
        .expect("regional locale"),
    );
    linguini_ir::validate_ir(&schema, &base).expect("base locale is independently valid");
    linguini_ir::validate_ir(&schema, &regional).expect("regional locale is independently valid");

    let error = ValidatedTypeScriptProject::try_new(
        &schema,
        &[
            TypeScriptLocaleModule {
                locale: "en".to_owned(),
                module: base,
            },
            TypeScriptLocaleModule {
                locale: "en-US".to_owned(),
                module: regional,
            },
        ],
        &TypeScriptProjectOptions {
            base_locale: Some("en".to_owned()),
            ..TypeScriptProjectOptions::default()
        },
    )
    .expect_err("invalid fallback composition must be rejected");

    let TypeScriptCodegenError::InvalidIr { scope, errors } = error else {
        panic!("expected invalid IR error");
    };
    assert_eq!(scope, "locale `en-US`");
    assert!(errors.iter().any(|error| error.code == "IR027"));
}

#[test]
fn project_codegen_emits_schema_namespace_objects() {
    use linguini_ir::{IrMessage, IrModule, IrText, IrTextBlockMode, IrTextPart};
    use linguini_syntax::Span;

    fn schema_message(name: &str) -> IrMessage {
        IrMessage {
            name: name.to_owned(),
            docs: Vec::new(),
            parameters: Vec::new(),
            body: None,
        }
    }

    fn locale_message(name: &str, value: &str) -> IrMessage {
        IrMessage {
            name: name.to_owned(),
            docs: Vec::new(),
            parameters: Vec::new(),
            body: Some(IrText {
                parts: vec![IrTextPart::Text(value.to_owned())],
                mode: IrTextBlockMode::Inline,
                span: Span::new(0, value.len()),
            }),
        }
    }

    let schema = IrModule {
        messages: vec![
            schema_message("checkout.order_ready"),
            schema_message("checkout.cart_summary"),
        ],
        ..IrModule::default()
    };
    let locale = IrModule {
        messages: vec![
            locale_message("checkout.order_ready", "Ready"),
            locale_message("checkout.cart_summary", "Cart"),
        ],
        ..IrModule::default()
    };

    let files = generate_project_files(
        &schema,
        &[TypeScriptLocaleModule {
            locale: "en".to_owned(),
            module: locale,
        }],
        &project_options("en"),
    )
    .expect("project codegen");

    let locale_module = files
        .iter()
        .find(|file| file.path == "locales/en.ts")
        .expect("locale module");
    assert!(locale_module
        .contents
        .contains("import { checkout } from \"./en/checkout\";"));
    assert!(locale_module.contents.contains("  checkout,"));

    let checkout_module = files
        .iter()
        .find(|file| file.path == "locales/en/checkout.ts")
        .expect("checkout locale module");
    assert!(checkout_module.contents.contains("order_ready: \"Ready\""));
    assert!(checkout_module.contents.contains("cart_summary: \"Cart\""));

    let declaration = files
        .iter()
        .find(|file| file.path == "locales/en.d.ts")
        .expect("locale declaration");
    assert!(declaration
        .contents
        .contains("export declare const checkout: typeof checkout;"));
}

#[test]
fn project_codegen_emits_generated_sveltekit_adapter_when_enabled() {
    use crate::{
        TypeScriptFramework, TypeScriptLocaleModule, TypeScriptProjectOptions, TypeScriptWebOptions,
    };
    use linguini_ir::IrModule;

    let files = generate_project_files(
        &IrModule::default(),
        &[TypeScriptLocaleModule {
            locale: "en".to_owned(),
            module: IrModule::default(),
        }],
        &TypeScriptProjectOptions {
            framework: Some(TypeScriptFramework::SvelteKit),
            web: Some(TypeScriptWebOptions {
                strategy: vec![
                    "url".to_owned(),
                    "cookie".to_owned(),
                    "header".to_owned(),
                    "baseLocale".to_owned(),
                ],
                cookie_name: "SHOP_LOCALE".to_owned(),
                cookie_path: "/shop".to_owned(),
                cookie_domain: Some("example.com".to_owned()),
                cookie_max_age: 86400,
                cookie_same_site: "strict".to_owned(),
                cookie_secure: true,
                cookie_http_only: true,
                local_storage_key: "SHOP_LOCALE".to_owned(),
                global_variable_name: Some("__SHOP_LOCALE__".to_owned()),
                prefix_default_locale: true,
                base_path: "/shop".to_owned(),
                trailing_slash: "never".to_owned(),
                redirect: false,
                origin: Some("https://example.com".to_owned()),
                exclude: vec!["/api/**".to_owned()],
                localize_links: false,
            }),
            ..project_options("en")
        },
    )
    .expect("project codegen");

    let paths = files
        .iter()
        .map(|file| file.path.as_str())
        .collect::<Vec<_>>();
    assert!(paths.contains(&"svelte.ts"));
    assert!(paths.contains(&"web.ts"));
    assert!(paths.contains(&"sveltekit.ts"));

    let svelte = files
        .iter()
        .find(|file| file.path == "svelte.ts")
        .expect("svelte module");
    assert!(svelte
        .contents
        .contains("import { createWebI18n } from \"./web\";"));
    assert!(!svelte.contents.contains("@antepod/"));
    assert!(svelte.contents.contains("export const l = linguini.l;"));
    assert!(svelte.contents.contains("cookieName: \"SHOP_LOCALE\""));
    assert!(svelte.contents.contains("localizeLinks: false"));
    assert!(svelte.contents.contains("cookie: true"));
    assert!(svelte.contents.contains("navigate: true"));
    assert!(svelte.contents.contains("keepFocus: true"));
    assert!(svelte.contents.contains("noScroll: true"));

    let sveltekit = files
        .iter()
        .find(|file| file.path == "sveltekit.ts")
        .expect("sveltekit module");
    assert!(sveltekit
        .contents
        .contains("import { createWebI18n } from \"./web\";"));
    assert!(!sveltekit.contents.contains("@antepod/"));
    assert!(sveltekit.contents.contains("export const handle"));
    assert!(sveltekit.contents.contains("export const reroute"));
    assert!(sveltekit.contents.contains("export const load"));
    assert!(sveltekit
        .contents
        .contains("cookie: event.request.headers.get(\"cookie\") ?? undefined"));

    let sveltekit_declaration = files
        .iter()
        .find(|file| file.path == "sveltekit.d.ts")
        .expect("sveltekit declaration");
    assert!(sveltekit_declaration
        .contents
        .contains("interface SerializedLinguiniContext"));
    assert!(sveltekit_declaration.contents.contains("interface Locals"));
    assert!(sveltekit_declaration
        .contents
        .contains("linguini: LinguiniRequestContext<Locale, Linguini>"));
    assert!(!sveltekit_declaration.contents.contains("@antepod/"));
}

#[test]
fn project_codegen_emits_context_only_svelte_without_web_config() {
    use crate::{TypeScriptFramework, TypeScriptLocaleModule, TypeScriptProjectOptions};
    use linguini_ir::IrModule;

    let files = generate_project_files(
        &IrModule::default(),
        &[TypeScriptLocaleModule {
            locale: "en".to_owned(),
            module: IrModule::default(),
        }],
        &TypeScriptProjectOptions {
            framework: Some(TypeScriptFramework::SvelteKit),
            web: None,
            ..project_options("en")
        },
    )
    .expect("project codegen");

    let paths = files
        .iter()
        .map(|file| file.path.as_str())
        .collect::<Vec<_>>();
    assert!(paths.contains(&"svelte.ts"));
    assert!(!paths.contains(&"web.ts"));
    assert!(!paths.contains(&"sveltekit.ts"));

    let svelte = files
        .iter()
        .find(|file| file.path == "svelte.ts")
        .expect("svelte module");
    assert!(svelte.contents.contains("activeLocale"));
    assert!(!svelte.contents.contains("$app/navigation"));
    assert!(!svelte.contents.contains("createWebI18n"));
}

#[test]
fn project_codegen_uses_cldr_text_direction_metadata() {
    use crate::{TypeScriptLocaleModule, TypeScriptProjectOptions};
    use linguini_ir::IrModule;

    let files = generate_project_files(
        &IrModule::default(),
        &[
            TypeScriptLocaleModule {
                locale: "en".to_owned(),
                module: IrModule::default(),
            },
            TypeScriptLocaleModule {
                locale: "ar".to_owned(),
                module: IrModule::default(),
            },
        ],
        &TypeScriptProjectOptions {
            base_locale: Some("en".to_owned()),
            ..TypeScriptProjectOptions::default()
        },
    )
    .expect("project codegen");

    let index = files
        .iter()
        .find(|file| file.path == "index.ts")
        .expect("index module");
    assert!(index.contents.contains(r#"en: "ltr""#));
    assert!(index.contents.contains(r#"ar: "rtl""#));
}
